src/features/tool-feedback/change-bounds-tool-feedback.ts, src/features/tools/change-bounds-tool.ts
- Avoid moving element when resizing
- Consider minimum width and height in change bounds tool
- Make change bounds tool more extensible with protected methods
Belongs to https://github.com/eclipse-glsp/glsp/issues/8
=> Avoid moving elements and consider minimum size when resizing

src/features/tools/change-bounds-tool.ts, src/utils/smodel-util.ts
With this change, we don't rely on the `positionDelta` for sending out mouse `ChangeBoundsActions` but only check whether we started dragging via `lastDragPosition`.
Resolves #22 and also fixes #21 while we're at it.
=> Fix mouse listener to always send out change bounds actions (#22)

src/features/tool-feedback/creation-tool-feedback.ts
Replace static `edge` type of the feebackEdgeSchema with the correct `elementTypeId`. Otherwise the feedback edge snapping does only work if the target is  connectable to the type `edge`
=> Fix feedback edge snapping

src/features/hover/di.config.ts, src/features/hover/hover.ts, src/features/validation/validate.ts, src/index.ts
* introduce dedicated GIssueMarker which enabled the SDecoration default
features including hovering
* introduce GlspHoverMouseListener which is able to identify hovering
over GIssueMarkers and displays a popup without a server roundtrip
* introduce glspHoverModule which binds the GlspHoverMouseListener for
the MouseListener type and export it
* add additional css class on parent element when adding marker
* clear this again when marker is cleared
Examples:
https://github.com/eclipse-glsp/glsp-examples/pull/33 (+ server fix for examples https://github.com/eclipse-glsp/glsp-server/pull/43)
=> Support popups for validation markers (#31)

src/features/change-bounds/movement-restrictor.ts, src/features/layout/layout-commands.spec.ts, src/features/layout/layout-commands.ts, src/features/tools/change-bounds-tool.ts, src/utils/layout-utils.ts, src/utils/smodel-util.ts
- Extract layout interfaces and utility methods to separate file
- Use utility methods in change-bounds-tool but still allow overriding
- Consider minimum size and movement restrictor in resize/align commands
- Fixes eclipse-glsp/glsp/issues/43
- Fixes eclipse-glsp/glsp/issues/27
Requires https://github.com/eclipse-glsp/glsp-theia-integration/pull/25
=> Layout command should respect minimum size and movement restrictor

css/glsp-sprotty.css, src/features/tool-feedback/css-feedback.ts, src/features/tools/change-bounds-tool.ts
- Fixes eclipse-glsp/glsp/issues/23
Please note that with snapping the mouse and the handles do not necessarily align anymore. For example, a snapping to a grid of size 10 with rounding values normally leads to a snap of the resize handle on a move change > 5, therefore the handle moves 'faster' than the mouse which has only moved 5 pixel. 
EDIT: After the great suggestion from Tobi, I now hide the mouse cursor and resizing feels much smoother! It is a bit surprising when the mouse cursor reappears but that is not really a big issue. Additionally, I now also highlight the currently active 'dragging' cursor:
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
=> Consider potential snapping in resize handles of change bounds tool

src/base/editor-context.ts, src/features/validation/validate.ts
This is to avoid an early dependency on the model source in case the editor context is used before the model source is bound.
=> Use model source provider in editor context

src/features/hints/type-hints.ts, src/utils/smodel-util.ts
Implement subtype support for element types based on a delimiter (:) similar to 
eclipse-glsp/glsp/issues/70.
=> Add subtype support for element typehints

src/base/actions/context-actions.ts, src/base/actions/edit-validation-actions.ts, src/base/args.ts, src/base/di.config.ts, src/base/editor-context.ts, src/base/operations/operation.ts, src/base/types.ts, src/features/context-menu/selection-service-aware-context-menu-mouse-listener.ts, src/features/navigation/di.config.ts, src/features/navigation/external-navigate-to-target-handler.ts, src/features/navigation/navigation-action-handler.ts, src/features/navigation/navigation-target-resolver.spec.ts, src/features/navigation/navigation-target-resolver.ts, src/features/validation/marker-navigator.ts, src/index.ts, src/model-source/websocket-diagram-server.ts
This change introduces navigation handling featuring
* server-based selection of navigation targets for a domain-specific navigation type id (e.g. definition, implementation, or next and previous) -- `RequestNavigationTargetsAction`
* server-based resolution of queries to elements to which the diagram should navigate -- `ResolveNavigationTargetAction`
* navigations to "external" resources handled by a dedicated external handler that can be bound by the outer application (Theia, Eclipse, etc.)
* possibility to trigger additional behavior when the server resolved elements via arguments
The meaning of all involved actions are documented in src/features/navigation/navigation-action-handler.ts.
Besides this change improves a few minors on the way:
* Fixes selection issue with context menu
* …
=> Support internal and external navigation and server-resolved navigations

css/decoration.css, src/features/decoration/decoration-placer.ts, src/features/decoration/di.config.ts, src/features/decoration/view.tsx, src/features/hover/hover.ts, src/features/validation/validate.ts, src/index.ts
- Introduce glspDecorationModule
- Use Theia issue marker icons as GlspIssueMarkers
- Add transparent svg rectangle to improve IssueMarker mouseover experience
- Fix applying severity CSS classes to model elements
- Use maximum severity as CSS class (similar to IssueMarkers)
- Extend IssueMarker tooltip message for better readability
Please also see my PR in glsp-examples, here is a short preview with different IssueMarkers:
=> Add IssueMarker decoration module

css/decoration.css, src/features/decoration/view.tsx
Remove rectangle overlay and replace with background circle which is filled with Theia editor background color to avoid that element details shine through
Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>
=> Add IssueMarker background circle

src/base/editor-context.ts, src/features/copy-paste/di.config.ts, src/features/layout/di.config.ts, src/features/layout/layout-commands.ts, src/features/save/di.config.ts, src/features/select/di.config.ts, src/features/select/selection-service.ts, src/features/validation/di.config.ts, src/index.ts
This is required in preparation for providing a more convenient way of defining Theia-native command handlers on GLSP diagrams.
Also, this change makes context menu providers of GLSP moduels optional. We'll provide Theia-native context menus to be used if the GLSP diagram is deployed in Theia. Finally, this change also adds some missing exports.
https://github.com/eclipse-glsp/glsp/issues/79
=> Add readonly SModel access in editor context

css/decoration.css, css/glsp-sprotty.css, css/tool-palette.css
The css stylesheets in @eclispe-glsp/client should be application/framework independent.
If needed, they can be overwritten by css files that are defined in the corresponding framework integration package (e.g. theia-integration)
Fixes https://github.com/eclipse-glsp/glsp/issues/98
=> #98 Remove theia-related css keys from @eclipse-glsp/client

src/features/tool-feedback/css-feedback.ts
- Fix ModifyCssFeedbackCommand to use elementId rather than element reference
=> FeedbackCommands should rely on elementId rather than element reference

package.json, src/base/actions/protocol-actions.ts, src/index.ts, src/model-source/websocket-diagram-server.ts, src/protocol/glsp-client.ts, src/protocol/glsp-jsonrpc-client.ts, src/protocol/index.ts, yarn.lock
- Clean up communication and move implementation into glsp client
- Define a "clean" `GLSPClient` interface that is independent from the underlying communication protocol
- Provide a base implementation for a jsonrpc-based `GLSPClient`
- Update dependencies to sprotty 0.9.0
- Align dependency versions with Theia versions
- Add new DisposeClientAction to notify the server if a specific diagram client/widget can be disposed (e.g. on editor tab close)
Part of:
- eclipse-glsp/glsp/issues/104
- eclipse-glsp/glsp/issues/94
- eclipse-glsp/glsp/issues/96
=> #94 #104 #96  Clean up communication protocol

packages/protocol/src/launch-util.ts
This enables reuse outside of Theia e.g. in VS Code
=> Migrate getPort function into @eclipse-glsp/protocol

packages/client/src/features/tool-feedback/css-feedback.ts, packages/client/src/utils/array-utils.ts
Adapt `ModifyCSSFeedbackAction` to support both a string[] with the smodel ids or a SModelElement[] as input.
=> Generalize input for ModifyCSSFeedbackAction

packages/client/src/base/auto-complete/auto-complete-widget.ts
Allow to change auto complete settings, suggestion provider, and
suggestion submit handler after instantiation. This is often used
in the onBeforeShow of UI extensions using the auto complete widget.
In the onBeforeShow we have more context and may want to change the
settings without having to reinstantiate the entire widget.
=> Make auto complete widget more flexible

packages/client/src/features/tools/node-creation-tool.ts, packages/client/src/index.ts, yarn.lock
Sprotty had a hard dependency on 5.0.1 which forced glsp-client to
also depend hard on 5.0.1. Theia however has ^5.0.1 which resolves
to 5.0.5, so we had a version mismatch.
We fixed this dependency in Sprotty and now we can upgrade the
Sprotty dependency in glsp-client to resolve the version mismatch
between glsp-client and glsp-theia-integration.
=> Upgrade Sprotty to fix inversify version mismatch

examples/workflow-glsp/src/di.config.ts, examples/workflow-glsp/src/workflow-views.tsx, packages/client/src/base/di.config.ts, packages/client/src/base/model/model-registry.ts, packages/client/src/base/view/view-registry.ts, packages/client/src/index.ts, packages/client/src/utils/argument-utils.ts, packages/client/src/views/base-view-module.ts, packages/client/src/views/default-types.ts, packages/client/src/views/glsp-edge-view.tsx, packages/client/src/views/index.ts, packages/client/src/views/issue-marker-view.tsx, packages/client/src/views/rounded-corner-view.tsx, packages/client/src/views/rounded-corner.ts
- Registrations
-- Provide default types as strings
-- Register elements for default types
-- Register views for default types
-- Ensure element and view registrations can be overwritten
- Views
-- Add rounded corner view that reads argument map for corner radius
-- Add edge view that supports custom padding for easier mouse handling
-- Move issue marker view to shared views folder
- Use custom edge and rounded corner view in example for new elements
Fixes https://github.com/eclipse-glsp/glsp/issues/180
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
=> #180: Provide default model and view registrations and add views

examples/workflow-glsp/css/diagram.css, examples/workflow-glsp/src/di.config.ts, examples/workflow-glsp/src/workflow-views.tsx, examples/workflow-standalone/app/example1.wf, examples/workflow-standalone/css/diagram.css
**Note:** Depends on https://github.com/eclipse-glsp/glsp-server/pull/107 being merged.
* Remove custom views that were only used to apply custom css classes
* TaskNodeView
* ForkOrJoinNodeView
* Use default Sprotty views instead and set css classes in the backend via SModelElement.cssClasses
* Adapt di config and diagram css
Signed-off-by: Lucas Koehler <lkoehler@eclipsesource.com>
=> #220 Rework workflow-example

package.json, packages/client/package.json, yarn.lock
Also add  update script to root package.json. The update script can be executed with `yarn upgrade:next`
Part of eclipse-glsp/glsp/issues/227
=> #227 Use concrete next version instead of tag

package.json, packages/client/package.json, yarn.lock
Revert back to using next tags after identifying issues for glsp-dependent projects that occurred with eclipse-glsp/glsp/issues/227.
We still want to maintain a "yarn upgrade:next" script in all repositories.
=> Revert #227

packages/client/src/features/tools/marquee-mouse-tool.ts
Pressing CTRL now keeps the previous selection when using the marquee tool
Signed-off-by: Simon Graband <sgraband@eclipsesource.com>
=> Keep selection when using CTRL and marquee tool

Jenkinsfile, examples/workflow-glsp/package.json, examples/workflow-standalone/package.json, package.json, packages/client/package.json, packages/protocol/package.json, yarn.lock
- Update metadata of all packages
- Add standalone eslint script `yarn lint`
- Add standalone build-only script (without linting) `yarn build`
Jenkinsfile
- Enable eslint reporting & publishing
- Move test execution into dedicated stage
- Only trigger deployment job if public package code was changed 
(part of eclipse-glsp/glsp/issues/229)
Part of: eclipse-glsp/glsp/issues/60
=> #60 #229 Cleanup and add codestyle reporting to ci

packages/client/src/features/copy-paste/copy-paste-context-menu.ts, packages/client/src/features/copy-paste/copy-paste-handler.ts
Switches mime type of clipboard ID to text/plain.
Prevents GLSP handling paste if the active element isn't the SVG element.
Tests whether copy, cut and paste commands are supported in the browser
to enable even paste in an Electron context.
Fixes https://github.com/eclipse-glsp/glsp/issues/249
=> Fix copy paste

packages/client/src/base/operations/operation.ts
The definition of the optional member variable location in ChangeContainerOperation does not match on server and client side.
Please see also server change: https://github.com/eclipse-glsp/glsp-server/pull/115
Fixes https://github.com/eclipse-glsp/glsp/issues/253
=> #253 Align operation definitions for ChangeContainerOperation

examples/workflow-standalone/src/main.ts, packages/protocol/src/glsp-client.ts, packages/protocol/src/jsonrpc/base-jsonrpc-glsp-client.ts
A client is already uniquely identified via its id, there is no need for an additional name property. In our current implementing projects the name property is always equal to the id and therefore redundant.
Part of eclipse-glsp/glsp/issues/258
=> #258 Remove name property from GLSPClient

packages/client/src/features/tool-feedback/change-bounds-tool-feedback.ts
- Fix element movement without selection for Firefox by avoiding reset of `startDragPosition` on mouse entering (similar to other Firefox fixes in sprotty)
Fixes https://github.com/eclipse-glsp/glsp/issues/376
=> #376 Element dragging without selection might not work with Firefox

.vscode/settings.json, package.json, packages/client/src/base/actions/edit-validation-actions.ts, packages/client/src/base/di.config.ts, packages/client/src/base/model/update-model-command.ts, packages/client/src/base/operations/operation.ts, packages/client/src/features/change-bounds/model.ts, packages/client/src/features/context-menu/di.config.ts, packages/client/src/features/tools/change-bounds-tool.ts, packages/client/src/features/tools/edge-edit-tool.ts, yarn.lock
Update to latest glsp-config version to consume https://github.com/eclipse-glsp/glsp/pull/405
(Update eslint-config to display formatting linting issues that get autofixed by prettier as warning)
(This is possible for all formatting linting rules except the "indent" rule. This rule has to be disabled. Prettier uses a dynamic indent size (e.g. spread objects (...) are formatted with two additional spaces, whereas es-lint only supports a static/fixed indent size. This causes unfixable warnings if the rule is activated. Prettier will still format and indent all lines correctly on save.
This means the developer should now get direct feedback in the editor again if there is a formatting issue like using " instead of ', multiple consecutive  empty lines, missing semicolons etc.
Also:
- Align …
=> #377 Update to latest glsp-config version

packages/protocol/src/action-protocol/element-text-editing.ts
This function wrongly checked for property `response`, while it actually should check for `repsonseId`.
=> Fix isSetEditValidationResultAction() function

.vscode/launch.json, examples/workflow-standalone/src/di.config.ts, packages/client/src/base/types.ts, packages/client/src/features/tools/marquee-behavior.spec.ts, packages/client/src/features/tools/marquee-behavior.ts, packages/client/src/features/tools/marquee-mouse-tool.ts, packages/client/src/index.ts
closes https://github.com/eclipse-glsp/glsp/issues/450
- Refactor code
- Move calculation code to new class for easy testing
- Return direct expression instead in if else
- Improve performance
- Cache possible elements at start, instead of collect them on each mouse move event
- Calculate absolute positions only once
- Add possibility to change the select behavior to marque full element
- Fix run test launch configs
- Add tests for calculation code of marquee tool
New marquee behavior:
I did again some performance measures in the MarqueeMouseListener class (same as in the Issue discribed):
* touch behavior: avg. 0.22880000030994416 ms
* touch behavior with 6x cpu slowdown: avg. 0.649664429910231 ms
* entire behavior: avg. 0.1789156626236726 ms
* entire behavior with 6x cpu slowdown: avg. …
=> #450 Improve Marquee tool (Performance & Full element marquee behavior)

packages/client/src/features/layout/di.config.ts
Note: there is one minor difference between the Sprotty registry and the one introduced in #470. When multiple layouts are bound to the same key, Sprotty logs a warning and rejects the new one; in the custom registry, since default layouts were not registered via dependency injection, we allowed overriding them (also after logging a warning).
We now have the expected Sprotty behavior: registering 2 different layouts on the same key is not allowed, and the first one wins. We must use rebind() instead.
=> 470: Remove custom LayoutRegistry and reuse the one from Sprotty

packages/client/src/features/tool-feedback/creation-tool-feedback.ts, packages/client/src/views/compartments.tsx
- Fix anchor computation for nested elements
Unrelated: remove the debug-attribute on Category compartments (Blue border around the compartment)
fixes eclipse-glsp/glsp/issues/224
=> 224: FeedbackEdge uses wrong child when used inside container element

packages/client/src/features/context-menu/selection-service-aware-context-menu-mouse-listener.ts, packages/client/src/features/hover/di.config.ts, packages/client/src/features/hover/hover.ts
* Restore focus of diagram after context menu is closed
* Cancel hover timer when diagram looses focus
* Clear hover state when diagram looses focus
Note that there is a separate hover issue with edges and handles, which is fixed in Sprotty directly. See https://github.com/eclipse/sprotty/issues/264
Fixes https://github.com/eclipse-glsp/glsp/issues/496
Fixes https://github.com/eclipse-glsp/glsp/issues/497
Contributed on behalf of STMicroelectronics.
=> Fix focus and hovering on context menu show/hide

packages/client/src/model-source/glsp-diagram-server.ts
The ExportSvgAction is now registered correctly again.
=> Fix diagram export

examples/workflow-glsp/css/diagram.css, examples/workflow-glsp/src/model.ts, examples/workflow-glsp/src/workflow-views.tsx, examples/workflow-standalone/app/example1.wf, packages/client/css/glsp-sprotty.css
https://github.com/eclipse-glsp/glsp/issues/492
=> Improve styling and simplfy workflow example

packages/client/src/features/select/selection-service.ts, packages/client/src/utils/smodel-util.ts, packages/protocol/src/utils/typeguard-util.ts
With eclipse-glsp/glsp-client/pull/167 a bug in the selection service was introduced. The `getSelectedElements()`  query method  returns
all `selectable` elements instead of the elements that are actually selected.
- Fix `SelectionService.getSelectedElements()` behavior. This also includes a performance improvement. We now only map the currently selected element ids to their SModelElement Instead of iterating over all elements of the index to receive the selected elements
- Introduce  a new  smodel util function that allows retrieving all model elements that correspond to a given set of element ids from the index.
- Introduce a `TypeGuard` convenience type to `typeguard-util`
Fixes eclipse-glsp/glsp/issues/602
=> #602 Fix SelectionService.getSelectedElements() method

packages/client/src/features/change-bounds/snap.spec.ts, packages/client/src/features/change-bounds/snap.ts, packages/client/src/features/tool-feedback/edge-edit-tool-feedback.ts, packages/client/src/features/tools/change-bounds-tool.ts, packages/client/src/features/tools/edge-edit-tool.ts
- Add snapping to mouseMove in FeedbackEdgeRouteMovingMouseListener
- Remove unused 'hasDragged' attribute from FeedbackEdgeRouteMovingMouseListener
Fixes: https://github.com/eclipse-glsp/glsp/issues/604
=> #604 Support snapping support for edges

packages/client/src/lib/model.ts, packages/client/src/views/base-view-module.ts, packages/protocol/src/model/default-types.ts
Disable `selectFeature` and `moveFeature` for the default foreign object configuration.
The select feature doesn't make sense for `ForeignObjectElements` as each DOMElement rendered from the objects `code` property
might provide it's own selection behavior. In addition this ensure that the resize feature also works for nodes that contain `ForeignObjectElements`.
Typically `ForeignObjectElement`s are children of a GNode so we also disable the move feature as nested child elements should not be movable.
Also: Add missing `Button` definition to default types and clean up imports of  `model.ts`
=> Improve default configuration for foreign objects

packages/client/src/base/editor-context-service.ts, packages/client/src/features/navigation/navigation-target-resolver.ts, packages/client/src/features/validation/validate.ts
Partly revert the changes made to the `EditorContextService` in  https://github.com/eclipse-glsp/glsp-client/pull/176 and make the `sourceUri` retrieval async again
Fixes eclipse-glsp/glsp/issues/633
=> #633 Make `EditorContextService.sourceUri` async again

packages/client/src/features/change-bounds/snap.ts
Make grid size of the `GridSnapper` configurable via constructor and setter.
Fixes https://github.com/eclipse-glsp/glsp/issues/652
=> GH-652 Configurable gridsnapper

packages/client/src/base/model/update-model-command.ts, packages/client/src/features/layout/di.config.ts, packages/client/src/features/mouse-tool/mouse-tool.ts
- Ensure that aciion promises are correctly dispatched  (I.e. non-blocking) in the `MouseTool`
- Fix animation flickering for routing point changes by Removing the `EdgeMorphAnimation` from the `UpdateModelCommand
(Also: Fix circular import of `AlignElementsActionHandler)
Fixes https://github.com/eclipse-glsp/glsp/issues/653
Fixes https://github.com/eclipse-glsp/glsp/issues/654
=> Fix mousetool action dispatching & routing point flickering

packages/client/src/features/context-menu/selection-service-aware-context-menu-mouse-listener.ts, packages/client/src/features/mouse-tool/mouse-tool.ts, packages/client/src/features/select/select-mouse-listener.ts, yarn.lock
- Update to latest sprotty version
- Update `SelectionServiceAwareContextMenuMouseListener` to use the `contextmenu` mouse event instead of the `right-click` event.
Fixes https://github.com/eclipse-glsp/glsp/issues/628
=> GH-628 Use generic context menu mouse event instead of right click event

CHANGELOG.md, packages/client/src/base/container-modules.ts, packages/client/src/features/source-model-watcher/di.config.ts, packages/client/src/features/source-model-watcher/source-model-changed-action-handler.ts, packages/client/src/index.ts, packages/protocol/src/action-protocol/element-navigation.ts, packages/protocol/src/action-protocol/model-data.spec.ts, packages/protocol/src/action-protocol/model-data.ts, packages/protocol/src/action-protocol/model-saving.ts
This is to be consistent with the term source model that we now use to refer to the underlying model from which the GModel is created.
https://github.com/eclipse-glsp/glsp/issues/655
=> Rename `ModelSourceChangedAction` to `SourceModelChangedAction`

examples/workflow-glsp/src/di.config.ts
Temporary remove usage of `GLSPProjectionView` in the workflow example. 
Can be readded once https://github.com/eclipse-glsp/glsp/issues/689 is resolved.
=> Update workflow example to not use `GLSPProjectionView`

examples/workflow-glsp/css/diagram.css, packages/client/src/features/layout/di.config.ts, packages/client/src/features/layout/hbox-layout.ts, packages/client/src/features/layout/layouter.ts, packages/client/src/features/layout/vbox-layout.ts
This PR depends on https://github.com/eclipse-glsp/glsp-server/pull/175
- Introduce a new StatefulLayouter, which applies layout in 2 passes: children -> parent for the "minimal size" (resizeContainer), then parent -> children to take the correct parent size into account for alignment (alignment, vGrab/hGrab)
- Update HBox and VBox layouts to take the new layouter into account
- Do not inherit child-specific layout properties (PrefSize, Grab)
- Properly take padding into account
- Update the Style for nested categories, to make them more readable (Add a border, use a different color for nested categories)
fixes https://github.com/eclipse-glsp/glsp/issues/694
fixes https://github.com/eclipse-glsp/glsp/issues/610
fixes https://github.com/eclipse-glsp/glsp/issues/471
Contributed on behalf of …
=> 694: Improve Layouter to support more dynamic layouts and complex parent/children node structures

examples/workflow-glsp/scripts/download.ts
Ensure that the snapshot version of the example server is downloaded
=> Update download server script

packages/client/src/features/layout/tests/freeform-layout.spec.ts, packages/client/src/features/layout/tests/hbox-layout.spec.ts, packages/client/src/features/layout/tests/layouter-test-util.ts, packages/client/src/features/layout/tests/vbox-layout.spec.ts
- Add hbox and vbox layouter tests (adapted and extended test cases from sprotty)
- Add freeform layouter tests according to #610 and #694 layouting problems
- Extract test util methods
Part of https://github.com/eclipse-glsp/glsp/issues/711
=> #711 Add test cases for improved Layouters

examples/workflow-glsp/src/di.config.ts, packages/client/src/views/glsp-projection-view.tsx
Fixes the [Broken Keylisteners](https://github.com/eclipse-glsp/glsp/issues/689) when using the GLSPProjection view by making the container `div` focusable.
=> Fix keylisteners when using 'GLSPProjectionView'

CHANGELOG.md, packages/client/package.json, packages/client/src/sprotty-reexport.ts, yarn.lock
Injecting a `ButtonHandler` constructor is deprecated by sprotty.
Stop reexporting the deprecated registration.
Reexport new registration method `configureButtonHandler`.
=> Update sprotty + use new button registration

packages/client/src/base/container-modules.ts, packages/client/src/features/bounds/di.config.ts, packages/client/src/features/bounds/glsp-hidden-bounds-updater.ts, packages/client/src/utils/smodel-util.ts, packages/protocol/src/action-protocol/model-layout.spec.ts, packages/protocol/src/action-protocol/model-layout.ts
Part of https://github.com/eclipse-glsp/glsp/issues/738
=> #738: Add route data to ComputedBoundsAction

packages/client/src/features/tools/di.config.ts, packages/client/src/features/tools/glsp-manhattan-edge-router.ts
This is not fixing the complete [issue as reported in Sprotty](https://github.com/eclipse/sprotty/issues/310) but mitigates the problem by making the routing point movable:
Relates to https://github.com/eclipse-glsp/glsp/issues/657
=> Allow the first Manhattan routing point to be moved

Jenkinsfile, examples/workflow-glsp/package.json, examples/workflow-standalone/package.json, package.json, packages/client/package.json, packages/protocol/package.json, yarn.lock
- https://github.com/eclipse-glsp/glsp/issues/676:
Update to lerna 6 and set node 14 as minimum engine version
- https://github.com/eclipse-glsp/glsp/issues/812:
Improve yarn scripts
- Remove linting from prepare step
- Add dedicated :ci scrips for testing and linting
- Add 'all' script on root level
- Consistently sort scripts ascending
- https://github.com/eclipse-glsp/glsp/issues/680: 
Update to latest `@eclipse-glsp/config` version
- https://github.com/eclipse-glsp/glsp/issues/794: 
Update Jenkinsfile to
- directly include deploy step instead of spawning a new dedicated job
- enable error reporting when master builds fail
=> Repo housekeeping

packages/client/package.json, packages/client/src/features/copy-paste/copy-paste-handler.ts
The `isDiagramActive` method of the copy-paste handler did check whether the active element is an instance of svg. 
In the case of the `GLSPProjectionView` this check failed because the SVG is contained by a wrapper container.
We can omit this part of the check entirely because we already know that the diagram is active if the parent of the active element is the `baseDiv`
Fixes https://github.com/eclipse-glsp/glsp/issues/827
=> Fix copy&paste support for GLSPProjectionView

CHANGELOG.md, packages/client/css/glsp-sprotty.css
Using glsp client on a custom layout is broken because of the global css applied to `svg`. all my application icons get a border.
The result I get from the standalone example
As this is my first contribution to the project please tell me if you have any CI for the changelog or if I need to update it by hand. (I am used to changeset but it is used here)
=> fix(diagram): scope css to avoid conflict on existing layout

CHANGELOG.md, packages/client/package.json, packages/client/src/base/command-stack.ts, packages/client/src/features/hover/hover.ts, packages/client/src/features/layout/layout-elements-action.ts, packages/client/src/features/select/select-mouse-listener.ts, packages/client/src/features/tool-feedback/change-bounds-tool-feedback.ts, packages/client/src/features/tool-feedback/creation-tool-feedback.ts, packages/client/src/features/tool-feedback/edge-edit-tool-feedback.ts, packages/client/src/sprotty-reexport.ts, packages/protocol/package.json, packages/protocol/src/action-protocol/element-creation.ts, packages/protocol/src/action-protocol/element-text-editing.ts, packages/protocol/src/action-protocol/undo-redo.spec.ts, packages/protocol/src/action-protocol/undo-redo.ts, yarn.lock
- Keep kind for DeleteElementOperation, UndoAction and RedoAction
Part of https://github.com/eclipse-glsp/glsp/issues/766
=> Upgrade Sprotty to consume label edit UI fix

examples/workflow-standalone/src/app.ts
UI extensions that should be active i.e. visible on startup might be activated to early (before the initial model loading is completed) which can cause rendering issues in some cases. This can be avoided by enabling these UI extensions after the model has been initialized. (see also https://github.com/eclipse-glsp/glsp/issues/585)
For the ToolPalette in particular this issue is not noticeable in the workflow diagram because the extension is activated after it has retrieved all tool palette items from the server. This typically takes longer than the initial model loading. Nevertheless we should simply establish the best practice of always enabling UI extensions after the model initialization.
=> Ensure that startup UI extensions are rendered correctly

examples/workflow-glsp/src/di.config.ts, examples/workflow-glsp/src/model.ts, packages/client/src/lib/model.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/855
So far I did not detect any side effects. If that keeps being true, we should contribute this back to Sprotty as well.
=> Add custom 'GEdge' that provides a 'localToParent' calculation

packages/client/src/features/tool-feedback/edge-edit-tool-feedback.ts
It seems that in Firefox the 'mouseEnter' event is fired directly after the 'mouseDown' event which caused us to reset the position. However, we should only reset the position if no moving is in progress (i.e., there is no current position tracking/dragging going on). But in that case there is no need to reset the position at all, therefore we can safely remove the 'mouseEnter' event handling for edge routing editing.
Fixes https://github.com/eclipse-glsp/glsp/issues/877
=> Ensure edge routing point can be grabbed in Firefox Browser

packages/protocol/src/utils/type-util.spec.ts, packages/protocol/src/utils/type-util.ts
Extends property check utility functions to also support checking of optional properties.
=> Extend type-util

CHANGELOG.md, packages/client/src/base/container-modules.ts, packages/protocol/src/utils/array-util.ts
Replace `ExcludeDescription`s with `ModuleConfiguration` which can be used for both adding (one or more) additional modules and removing (one or more)  default modules. This makes the entire configuration process more convenient.
For example:
```ts
const container= createDiagramContainer(myModule1, myModule2, { exclude: toolsModule}, myToolsModule, {exclude: toolPaletteModule}, myToolPaletteModule)
```
can now be configured as follows
```ts
const container= createDiagramContainer({
add:[myModule1,myModule2,myToolsModule,myToolPaletteModule],
remove:[toolsModules,toolPaletteModule]})
```
Naturally its also possible to directly include modules and use multiple module configurations e.g:
```ts
const container= createDiagramContainer(myModule1, myModule2, {remove: toolsModule, …
```
=> Refactor `createDiagramContainer` function

packages/protocol/src/action-protocol/model-layout.ts
Align definition with sprotty's definition which also allows optional elementIds.
@xai Please also adpat in https://github.com/eclipse-glsp/glsp-website-source/pull/81
=> Fix definition  of `LayoutOperation`

packages/protocol/src/action-protocol/element-validation.spec.ts, packages/protocol/src/action-protocol/element-validation.ts
https://github.com/eclipse-glsp/glsp/issues/980
=> Add missing `reason` to `SetMarkersAction`

packages/protocol/src/client-server-protocol/glsp-client.ts, packages/protocol/src/client-server-protocol/glsp-server.ts, packages/protocol/src/client-server-protocol/types.ts, packages/protocol/src/index.ts, packages/protocol/src/jsonrpc/base-jsonrpc-glsp-client.ts, packages/protocol/src/jsonrpc/glsp-jsonrpc-client.ts, packages/protocol/src/jsonrpc/glsp-jsonrpc-server.ts
Ensures that the `@eclipse-glsp/protocol` package also provides the glsp server interfaces. This allows type reusage in usecases where the GLSP server is not running in an external process and is instead accessed directly.
Part of https://github.com/eclipse-glsp/glsp/issues/975
=> GLSP-975 Move glsp-server types into protocol packages

packages/protocol/src/jsonrpc/base-jsonrpc-glsp-client.ts
`GLSPClientProxy` was accidentally imported from the main index. This can cause circular dependency issues with inversify -> package internal dependencies should never use the main index.
=> Fix wrong import

packages/protocol/src/client-server-protocol/base-glsp-client.spec.ts, packages/protocol/src/client-server-protocol/base-glsp-client.ts, packages/protocol/src/client-server-protocol/glsp-server.ts, packages/protocol/src/client-server-protocol/jsonrpc/base-jsonrpc-glsp-client.ts, packages/protocol/src/client-server-protocol/jsonrpc/glsp-jsonrpc-server.ts, packages/protocol/src/index.ts
The `NodeGLSPClient` can also be used in a browser context => rename to `BaseGLSPClient`. This way we can introduce a consistent naming scheme for generic base client implementations: `Base<communication-channel>GLSPClient`. 
For instance if are going to provide a REST implementation in the future it could be called `BaseRestGLSPClient`.
=> GLSP-975: Rename `NodeGLSPClient`

packages/protocol/src/client-server-protocol/jsonrpc/websocket-connection.ts
Adapt send() method of the `WebSocketWrapper` to support all types that are supported by the underlying websocket send method as well.
=> Adjust WebSocketWrapper

packages/client/src/features/accessibility/move-zoom/di.config.ts, packages/client/src/features/accessibility/move-zoom/move-handler.ts, packages/client/src/features/accessibility/move-zoom/zoom-handler.ts, packages/client/src/features/accessibility/view-key-tools/deselect-key-tool.ts, packages/client/src/features/accessibility/view-key-tools/di.config.ts, packages/client/src/features/accessibility/view-key-tools/movement-key-tool.ts, packages/client/src/features/accessibility/view-key-tools/zoom-key-tool.ts, packages/client/src/index.ts
This PR is part of my diploma research conducted at the [Model Engineering lab](https://me.big.tuwien.ac.at/) of TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/). It introduces the **move** and **zoom** functionality.
1. Select one or multiple elements
2. Use the arrow keys to move the element(s) accordingly
1. Focus is on viewport , no elements are selected
2. Use the arrow keys to move the viewport accordingly
1. Select one or multiple elements
2. Use `+` or `-` to zoom in/out  into the direction of the element or elements
3. Use `CTRL + 0` to reset to default zoom level
1. Focus is on viewport , no elements are selected
2. Use `+` or `-` to zoom in/out in viewport
3. Use `CTRL + 0` to reset to default zoom level
@martin-fleck-at, @ndoschek
Part of …
=> Add keyboard support for moving and zooming elements and viewport

packages/client/src/features/accessibility/resize-key-tool/di.config.ts, packages/client/src/features/accessibility/resize-key-tool/resize-key-handler.ts, packages/client/src/features/accessibility/resize-key-tool/resize-key-tool.ts, packages/client/src/index.ts
This PR is part of my diploma research conducted at the [Model Engineering lab](https://me.big.tuwien.ac.at/) of TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/). It introduces the **resize** functionality.
1. Select one or multiple elements
2. Use the shortcut  `ALT + A` to activate the resize mode
3. Use the keys  `+` or  `-` to resize the element accordingly
4. Use `CTRL + 0` to reset to default size 
1. The shortcut `ALT + A` is necessary, as later, `+` or  `-` , will also be used for other functionalities (e.g. zoom).
2. In a different PR, a user notification will be displayed if the mode is activated.
@martin-fleck-at, @ndoschek
Part of https://github.com/eclipse-glsp/glsp/issues/1029
=> Add keyboard support for resizing elements

packages/client/src/features/tool-feedback/change-bounds-tool-feedback.ts, packages/client/src/features/tools/change-bounds-tool.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/941
How I tested this:
1. move and resize elements and then hit Escape to see if the feedback is properly reset
2. install a timer to periodically send an updatemodelaction from the server and see if the visual feedback for move isn't disturbed and correctly re-applied after each model update from the server
=> Use feedback dispatcher for change bounds feedback

examples/workflow-standalone/src/app.ts, packages/protocol/src/client-server-protocol/jsonrpc/ws-connection-provider.ts, packages/protocol/src/index.ts
- Introduce GLSPWebSocketProvider to allow websocket connections to reconnect after interrupt
- Make use of ws provider in standalone example
Part of https://github.com/eclipse-glsp/glsp/issues/77
---
Related to: https://github.com/eclipse-glsp/glsp-server-node/pull/54
Related to: https://github.com/eclipse-glsp/glsp-server/pull/208
Testing:
- To simulate interrupts, you can use the corresponding testing branch [`issues/77-testing`](https://github.com/eclipse-glsp/glsp-client/tree/issues/77-testing). This automatically interrupts the example twice with an timeout of 5s in between.
=> GLSP-77: Allow WebSocket connections to reconnect after interrupt

.eslintrc.js, .gitignore, README.md, examples/workflow-standalone/package.json, examples/workflow-standalone/scripts/config.json, examples/workflow-standalone/scripts/start-example-server.ts, package.json, yarn.lock
Remove direct dependency in `@eclipse-glsp/client` and add dedicated download & start script instead. This resolves the circular dependency issues between glsp-client and server-node and unblocks us for releases.
Fixes https://github.com/eclipse-glsp/glsp/issues/1026
=> GLSP-1026 Resolve circular dependency between client and node-server

packages/client/css/key-shortcut.css, packages/client/src/features/accessibility/key-shortcut/accessible-key-shortcut-tool.ts, packages/client/src/features/accessibility/key-shortcut/accessible-key-shortcut.ts, packages/client/src/features/accessibility/key-shortcut/di.config.ts, packages/client/src/features/accessibility/resize-key-tool/resize-key-tool.ts, packages/client/src/features/accessibility/search/search-tool.ts, packages/client/src/features/accessibility/view-key-tools/movement-key-tool.ts, packages/client/src/features/accessibility/view-key-tools/zoom-key-tool.ts, packages/client/src/index.ts
This PR is part of my diploma research conducted at the [Model Engineering lab](https://me.big.tuwien.ac.at/) of TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/). It introduces a list of existing keyboard shortcuts.
1. Focus is on viewport.
2. Use the shortcut  `ALT+H` to display the list of keyboard shortcuts.
@ndoschek @martin-fleck-at 
Part of https://github.com/eclipse-glsp/glsp/issues/1029
=> Introduce list of keyboard shortcuts

packages/client/src/features/select/select-mouse-listener.ts
Update selection-mouse listener. The base mouse listener in sprotty has been reworked. This change adjusts the `RankedSelectMouseListener` to the new basae implementation and overrides it where necessary to avoid disposal of `SetEditModeActions`
Fixes https://github.com/eclipse-glsp/glsp/issues/1082
=> GLSP-1082: Fix edge edit

examples/workflow-glsp/src/workflow-diagram-module.ts, examples/workflow-standalone/src/app.ts, examples/workflow-standalone/src/di.config.ts, packages/client/src/base/default.module.ts, packages/client/src/base/editor-context-service.ts, packages/client/src/base/model/diagram-loader.ts, packages/client/src/base/model/glsp-model-source.ts, packages/client/src/default-modules.ts, packages/client/src/features/hints/type-hints-module.ts, packages/client/src/features/hints/type-hints.ts, packages/client/src/features/navigation/navigation-target-resolver.ts, packages/client/src/features/status/status-module.ts, packages/client/src/features/status/status-overlay.ts, packages/client/src/features/tool-palette/tool-palette-module.ts, packages/client/src/features/tool-palette/tool-palette.ts, packages/client/src/features/validation/validate.ts, packages/client/src/glsp-sprotty/types.ts, packages/client/src/index.ts, packages/protocol/src/client-server-protocol/base-glsp-client.spec.ts, packages/protocol/src/client-server-protocol/base-glsp-client.ts, packages/protocol/src/client-server-protocol/glsp-client.ts, packages/protocol/src/client-server-protocol/jsonrpc/base-jsonrpc-glsp-client.spec.ts, packages/protocol/src/client-server-protocol/jsonrpc/base-jsonrpc-glsp-client.ts
- Make import configuration constants available in DI container via `IDiagramOptions`. This includes diagramType, clientId, sourceUri and glspClient.
- Introduce `DiagramLoader` as new central component responsible for configuring the glsp client and dispatching the intial model loading request
- Introduce `IDiagramStartup` services that can hook into the diagram loader lifecycle (GLSP-587)
- This means that feature modules are now self containted and can dispatch their initial actions, activate UI extensions on startup etc. without having to modifiy the `GLSPDiagram` (or similiar) componenent.
- Add `onServerInitialized` event + tests to `GLSPClient`
Part of https://github.com/eclipse-glsp/glsp/issues/960 
Part of https://github.com/eclipse-glsp/glsp/issues/587
=> GLSP-960 Improve Diagram container configuration

packages/client/src/views/glsp-projection-view.tsx
We should compute all routes at once in order to enable edge route postprocessors and with that also the intersection detection. When only computing one route after the other we cannot detect intersections and thus don't render gaps on edge intersections.
Fixes https://github.com/eclipse-glsp/glsp/issues/1084
=> Add edge routing in GLSP projection view

packages/client/src/base/focus/focus-tracker.ts, packages/client/src/features/tool-palette/tool-palette.ts
- UI extensions only track the active element before they are shown
- Enhance the focus tracker to provide more info on the active element
-- In Theia the tool palette stored the file explorer as active element
Requires https://github.com/eclipse-glsp/glsp-theia-integration/pull/174
Fixes https://github.com/eclipse-glsp/glsp/issues/1088
=> GLSP-1088: Ensure we restore focus to the diagram

examples/workflow-glsp/src/workflow-diagram-module.ts, examples/workflow-standalone/src/di.config.ts
The a11y module is currently only tested for the standalone example but is configured per default in the global workflow glsp config. 
=> Remove module from global config and only enable it in the standalone example
=> Only enable a11y module in standalone example

packages/client/src/features/hover/hover.ts, packages/client/src/views/base-view-module.ts
Ensure that hover support for manually constructed issue markers works as expected.
The hover mouse listener checks for `GIssueMarkers` but we configure issue markers as `SIssueMarkers` per default
=> Fix hover support for issue markers

examples/workflow-standalone/src/app.ts, packages/client/src/base/model/diagram-loader.ts, packages/client/src/base/model/glsp-model-source.ts
Provide `DiagamLoaderOptions` to support dynamic configuration of the loading behavior
Follow-up for eclipse-glsp/glsp/issues/960
=> GLSP-960: Follow-up

packages/client/src/features/context-menu/glsp-context-menu-mouse-listener.ts, packages/client/src/features/copy-paste/copy-paste-modules.ts, packages/client/src/features/copy-paste/copy-paste-standalone.ts, packages/client/src/features/viewport/viewport-handler.ts, packages/client/src/standalone-modules.ts
- Add copy-paste support for standalone via keyboard short cuts
- Trigger auto layout operation via keyboard short cut (Shift+ctrl+L)
- Ensure that the viewport handler does not steal focus when integrated in an application frame (i.e. Theia)
- Make context menu listener selection aware. If the context menu was triggered for a selectable target (or parent):
do nothing if the element is already selected, otherwise set the selection to the selectable element
Remove the current selection if the context menu element is not selectable. This behavior is consistent with other graphical tools like DrawIO, Google drawings, Papyrus etc.
=> Bugfixes for 2.0.0

package.json
The `--preid` flag was omitted on accident in a previous commit. As a consequence nightly versions are now published as "alpha".
Readd correct preid.
(https://www.npmjs.com/package/@eclipse-glsp/client/v/2.1.0-alpha.290)
=> Use `next` preid for nightly publishing

packages/client/src/base/model/diagram-loader.ts, packages/client/src/default-modules.ts
Sprotty introduced zoom limits, so we should allow setting them.
This change allows to optionally specify all `ViewerOptions` in `configureDiagramOptions` and sets very generous `zoomLimits` by default. This should also mitigate the bug when you zoom beyond `Number.maxValue`.
=> Allow setting `ViewerOptions` and set default zoom limits

packages/client/src/features/accessibility/move-zoom/move-handler.ts, packages/client/src/features/accessibility/resize-key-tool/resize-key-handler.ts, packages/client/src/features/accessibility/search/search-palette.ts, packages/client/src/features/accessibility/view-key-tools/movement-key-tool.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool-feedback.ts, packages/client/src/utils/viewpoint-util.ts
* Show client-side feedback without animation
* Trigger server operation with a debounce delay
* Respect snap modifier (ALT) for move
* Respect movement restrictor for move
Can only be tested with the standalone workflow example!
Fixes https://github.com/eclipse-glsp/glsp/issues/1156
=> Keyboard move and resize improvements

examples/workflow-standalone/scripts/config.json
Ensure that the server download script downloads the latest version of the bundled workflow-server.
(The 2.0.0 version was bundled incorrectly and this was hotfixed with 2.0.1)
=> Fix download example-server script

packages/client/src/base/default.module.ts, packages/client/src/base/selection-service.ts
Avoid binding of SelectionService as `IModelRootListner`. Instead directly inject the`CommandStack` into `SelectionService` and manually register itself as `IGModelRootListener`. This avoids a circular dependency injection if any of the `SelectionListner`s wants to inject the `ActionDispatcher`.
Can be tested e.g. by creating a `SelectionListener` that injects the action dispatcher:
```ts
@injectable()
export class MySelectionListener implements ISelectionListener {
@inject(TYPES.IActionDispatcher)
protected actionDispatcher: ActionDispatcher;
selectionChanged(root: Readonly<GModelRoot>, selectedElements: string[], deselectedElements?: string[] | undefined): void {
console.log('Selection changed: ' + selectedElements);
}
}
// bind it in the workflow diagram module
bindAsService(context, …
```
=> GLSP-1166 Fix dependency injection cycle in selection service

CHANGELOG.md, packages/protocol/src/client-server-protocol/jsonrpc/base-jsonrpc-glsp-client.spec.ts, packages/protocol/src/client-server-protocol/jsonrpc/base-jsonrpc-glsp-client.ts
Fixes  https://github.com/eclipse-glsp/glsp/issues/1181
Also: Update changelog to reflect latest changes
=> GLSP-1181: Fix support for simultaneously open diagrams

packages/client/src/base/selection-service.spec.ts, packages/client/src/base/selection-service.ts
When we receive a model update and the selection state (ids of selected elements) stays the same, we should not send out a selection changed event. Code interested in model updates can listen to root changes manually. This also prevents Theia from permanently updating the selection if only the root element was changed.
Fixes https://github.com/eclipse-glsp/glsp/issues/1194
This can be tested with a Node server that sends an update every second, see https://github.com/eclipse-glsp/glsp-server-node/tree/issues/1194_test
=> GLSP-1194: Do not send out selection changes if only the root changed

packages/protocol/src/utils/index.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/1269
Verify through another package that does not have chai but still imports types and functions from the main package that it properly works.
=> Avoid dependency on 'chai' through exported index

packages/client/src/features/helper-lines/helper-line-feedback.ts
- Use <= as comparison operator
- Do not match for feedback edge
Fixes https://github.com/eclipse-glsp/glsp/issues/1257
When binding the `IHelperLineOptions` in `workflow-diagram-module`, set the `alignmentEpsilon` to zero and observe that now we properly match the zero-epsilon condition.
=> Fix helper line feedback matching

packages/client/css/ghost-element.css, packages/client/css/glsp-sprotty.css, packages/client/src/features/bounds/glsp-hidden-bounds-updater.ts, packages/client/src/features/bounds/local-bounds.ts, packages/client/src/features/bounds/set-bounds-feedback-command.ts, packages/client/src/features/element-template/add-template-element.ts, packages/client/src/utils/gmodel-util.ts, packages/glsp-sprotty/src/re-exports.ts
- Do not use 'display: none' for hidden getBBox() calculation
- Only re-calculate the bounds for certain elements -- Extend LocalRequestBoundsAction with element IDs -- Restrict calculation to given set of elements if IDs are present
- Minor: Fix re-export for decorationModule
Fixes https://github.com/eclipse-glsp/glsp/issues/1258
- Resize elements or create new elements in the workflow example using the ghost elements (default).
- Check that we have the same visual feedback in both Chrome, Firefox or any other browser you are using
=> Ensure hidden bounds calculation works in all browser

packages/client/src/default-modules.ts, packages/client/src/features/command-palette/command-palette-module.ts, packages/client/src/features/command-palette/command-palette.ts, packages/client/src/features/command-palette/index.ts, packages/client/src/features/label-edit-ui/label-edit-ui-module.ts, packages/client/src/features/label-edit-ui/label-edit-ui.ts, packages/glsp-sprotty/css/ui-extension.css, packages/glsp-sprotty/src/feature-modules.ts, packages/glsp-sprotty/src/re-exports.ts, packages/glsp-sprotty/src/ui-extension-override.ts
- Allow more fine-grained definition of container and parent
- Allow more fine-grained definition of container within parent
- Replace hard-coded styles with 'hidden' class
Fixes https://github.com/eclipse-glsp/glsp/issues/1246
Fixes https://github.com/eclipse-glsp/glsp/issues/1318
- Check whether the known UI extensions (command palette, label edit, tool palette) still work as expected
- Check whether the fade animation is no longer visible in the Theia integration (for https://github.com/eclipse-glsp/glsp/issues/1246)
None.
=> Improve UI Extension mechanism for easier re-use of HTML elements

packages/client/src/base/model/diagram-loader.ts, packages/client/src/features/viewport/viewport-handler.ts
- Refactor `DiagramLoader` to catch and log errors that occur when invoking startup hooks
- This ensures both: failure of one hook does not affect execution of following hooks and if  a hook fails for any reason we provide the reason in the log output
- Refactor `RestoreViewportHandler` to use the actual dom id of the root element for querying/focusing the graph. This ensures that the focusing also works if the root model element is not of type `graph`.
Fixes https://github.com/eclipse-glsp/glsp/issues/1309
=> GLSP-1309: Improve error handling of startup hooks

packages/protocol/src/client-server-protocol/jsonrpc/worker-connection-provider.ts
Since most of the functionality is already provided by `vscode-jsonrpc`, I merely created a rather simple wrapper in order to conform to the already existing web socket implementation.
=> Implemented webworker connection provider

packages/client/src/features/copy-paste/copy-paste-standalone.ts
Default event prevention should be handled by the `ICopyPasteHandler` implementation. e.g. The default `ServerCopyPasteHandler` has guard clauses to check wether a copy or paste operation should be executed (diagram must be active and selection >0). It only default prevents if this condition is met. Currently we bypass this special check and always default prevent which causes issues in scenarios where the diagram is nested into a surrounding application frame or is currently not focused (e.g.) hidden.
See also https://github.com/eclipse-glsp/glsp/discussions/1331
=> Remove eager default prevention from standalone copy paste handlder

packages/client/css/change-bounds.css, packages/client/src/base/mouse-position-tracker.ts, packages/client/src/features/debug/debug-manager.ts, packages/client/src/features/grid/grid-manager.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool-move-feedback.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool.ts, packages/client/src/features/tools/edge-creation/edge-creation-tool.ts, packages/client/src/features/tools/edge-edit/edge-edit-tool-feedback.ts, packages/client/src/features/tools/edge-edit/edge-edit-tool.ts, packages/glsp-sprotty/src/svg-views-override.tsx
- Ensure GridManager properly tracks state if action is used on startup
- Ensure DebugManager properly tracks state if action is used on startup
- Avoid cursor feedback interfering with edge edit feedback in disposal
- Avoid unnecessary disposal calls by calling mouseUp on mouseMove
- Fix issue with non-resizable elements not being movable
- Fix calculation of position on diagram for nested HTML elements
- GridManager/DebugManager: Send a ShowGridAction, EnableDebugModeAction on startup and see that the feedback is applied even after a server update (e.g., move an element).
- Feedback edge: Edit an edge and hit 'Escape' in the middle, ensure that feedback edge is properly disposed.
- Element Move: Remove the resize feature (or typehint) from an element on the server, check whether in can …
=> Improve some aspects of change bounds, feedback and positioning

packages/client/src/features/export/glsp-svg-exporter.ts
For some reason our created target elements are not actually instanceof Element even though everything is in their prototype chain. So instead, we now check whether it is an element with tag (HTML, SVG, Math) and whether it has a style property.
- Debug and you'll see that we do not keep the style of SVG elements etc.
=> Fix style handling in SVG exporter

examples/workflow-glsp/src/workflow-diagram-module.ts, packages/client/src/features/accessibility/accessibility-module.ts, packages/client/src/features/accessibility/element-navigation/element-navigation-module.ts, packages/client/src/features/accessibility/focus-tracker/focus-tracker-module.ts, packages/client/src/features/accessibility/key-shortcut/shortcut-help-module.ts, packages/client/src/features/accessibility/toast/toast-module.ts, packages/client/src/features/accessibility/view-key-tools/deselect-key-tool.ts, packages/client/src/features/change-bounds/model.ts, packages/client/src/features/change-bounds/movement-restrictor.ts, packages/client/src/features/helper-lines/helper-line-manager-default.ts, packages/client/src/features/select/select-mouse-listener.ts, packages/client/src/features/tools/change-bounds/change-bounds-manager.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool-module.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool-move-feedback.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool.ts, packages/client/src/features/tools/change-bounds/change-bounds-tracker.ts, packages/client/src/features/tools/change-bounds/view.tsx, packages/client/src/features/undo-redo/undo-redo-module.ts, packages/client/src/index.ts
- Adjust name of `SResizeHandle` and `SResizeHandleview` to the gmodel namespace
and reexport under the old name as deprecated for backwards compatibility.
- Ensure that all diagram modules are constructed as `FeatureModules` instead of plain `ContainerModules`
- Rename modules that still have the glsp prefix and also reexport under old deprecated name
=> Minor cleanup & deprecations

packages/client/src/features/grid/grid-style.ts, packages/client/src/index.ts, packages/client/src/views/ggraph-view.tsx, packages/client/src/views/glsp-projection-view.tsx
- Ensure grid is applied on normal graph view without projections
- Allow grid color to be specified through CSS
- Add more properties to the graph for re-use
- Test graph view and graph projection view and try to change the grid color through CSS
=> Enhance Grid functionality and customizability

examples/workflow-glsp/src/direct-task-editing/direct-task-editor.ts, packages/client/src/base/auto-complete/base-autocomplete-palette.ts, packages/client/src/features/accessibility/key-shortcut/accessible-key-shortcut.ts, packages/client/src/features/accessibility/keyboard-grid/keyboard-grid.ts, packages/client/src/features/accessibility/keyboard-pointer/keyboard-pointer.ts, packages/client/src/features/accessibility/toast/toast-tool.ts, packages/client/src/features/label-edit-ui/label-edit-ui.ts, packages/client/src/features/status/status-overlay.ts, packages/client/src/features/tool-palette/tool-palette.ts
- Use our GLSPAbstractUIExtension instead of AbstractUIExtension
- Fix focus issue with GlspEditLabelUI
- Ensure that whenever you show the label edit UI, the text field gets proper focus
- Test other UI extensions behave as before
=> Fix issue with UI extensions

packages/client/src/features/tools/change-bounds/change-bounds-tool.ts, packages/protocol/src/di/container-configuration.ts
- Ensure that the change bounds tool does not dispatch `ChangeRoutingPointsAction` if there are not valid element moves.
- Ensure that duplicate detection in `resolveContainerConfiguration` properly stringifies symboles.
=> Fix issue with change bounds tool

examples/workflow-glsp/src/direct-task-editing/task-editor-module.ts, examples/workflow-glsp/src/workflow-diagram-module.ts, examples/workflow-standalone/css/command-palette.css, examples/workflow-standalone/src/di.config.ts, examples/workflow-standalone/src/features/direct-task-editing/standalone-task-editor-module.ts, examples/workflow-standalone/src/features/direct-task-editing/task-editor-key-listener.ts, packages/client/package.json, packages/client/src/base/auto-complete/auto-complete-widget.ts, packages/glsp-sprotty/package.json, packages/protocol/package.json, yarn.lock
- Update `onSelect` method of autocomplete Widget to dispatch a `input` event instead of a `keyup` event. (Since autocompleter 8.x the suggestion update uses `input` instead of `keyup`
- Enable task editor in standalone example by adding an explicit standaloneTaskEditorModule. Fixes https://github.com/eclipse-glsp/glsp/issues/1347
In addition:
- Update dependencies and align with sprotty
- Use fixed version of vscode-jsonrpc to avoid conflicts with Theia
- Restore original container configuration order in `workflow-diagram-module` (was changed on accident in https://github.com/eclipse-glsp/glsp-client/pull/355)
- Trigger task editing mode by selectin a task then press Ctrl+F2
- Verify that task editing works as expected. 
-  Applying suggestions + validation 
-   [x] This PR should be …
=> GLSP-1347: Fix autocomplete widget

.eslintrc.js, examples/workflow-glsp/src/workflow-diagram-module.ts, examples/workflow-glsp/src/workflow-views.tsx, packages/client/css/grid.css, packages/client/src/default-modules.spec.ts, packages/client/src/features/debug/debug-bounds-decorator.tsx, packages/client/src/features/helper-lines/view.tsx, packages/client/src/features/tools/change-bounds/view.tsx, packages/client/src/features/tools/edge-creation/view.tsx, packages/client/src/features/tools/marquee-selection/view.tsx, packages/client/src/features/tools/node-creation/node-creation-views.tsx, packages/client/src/views/compartments.tsx, packages/client/src/views/gedge-view.tsx, packages/client/src/views/ggraph-view.tsx, packages/client/src/views/glsp-projection-view.tsx, packages/client/src/views/issue-marker-view.tsx, packages/client/src/views/rounded-corner-view.tsx, packages/glsp-sprotty/src/svg-views-override.tsx
- Refactor grind background image rendering to a css only approach
- Use @jsx annotion for view files Use @jsx annotation instead of const JSX definition for view files. Adapt eslint config to ignore  unused svg and html imports to avoid explict deactivation of the rule in each view file. Reason:
- Sprotty base views also use annotations
- Annotations are more robust. E.g. mocha tests with ts-node fail with an unused local error   when using JSX const
- Add tests for `initializeDiagramContainer`
- Cleanup GLSPProjectionView overrides
=> View improvements

CHANGELOG.md, examples/workflow-standalone/app/example1.wf, packages/client/css/glsp-sprotty.css, packages/client/src/base/action-dispatcher.ts, packages/client/src/base/command-stack.ts, packages/client/src/base/default.module.ts
- Update example1.wf
- Remove projection specific css styles for hiding the projection bars on mouse enter/leave over the diagram. This is not a generic feature only certain integration types support it (Theia//VS Code) so it should be handled in the integration specific code base
-  Fix timing issue in `GLSPCommandStack` when notifying `GModelRootListeners` after a model change. Properly wait until the listeners a notified before completing the returned promise. This ensures that all model listeners have received the updated model information before the next action is processed by the dispatcher.
- Introduce `dispatcherAfterNextUpdate` method in `GLSPActionDispatcher` that allows to delay the dispatching of actions until the next model update is processed from the server. (Now actions …
=> Minor improvements

CHANGELOG.md, packages/client/src/base/tool-manager/tool-manager.ts, packages/client/src/features/context-menu/glsp-context-menu-mouse-listener.ts, packages/client/src/features/grid/grid-style.ts
- Add `defaultToolsEnabled` flag to `ToolManager` which is true if currently only the default tools are enabled i.e. no tools have been enabled explicitly
- Avoid (re)activation of default tools if the are already enabled
- Remove unused GRID_STYLE property
=> Improve ToolManagerAPI

packages/client/src/features/element-template/mouse-tracking-element-position-listener.ts, packages/client/src/features/tools/node-creation/node-creation-tool.ts
When in stamp mode when you move the mouse while the creation of a node using ghost feedback is still on-going, you will see that the mouse cursor and the ghost feedback will get out of sync. The reason is that there are no mouse events for some time until the diagram is properly re-rendered. We therefore re-initialize tracking position once we have a new root element.
- Use Stamp mode (keep Ctrl pressed)
- Create a node, keep moving the mouse during creation
- Check if ghost element is properly aligned
=> Fix: Proper alignment of ghost element after update in continuous mode

packages/client/src/base/selection-service.spec.ts, packages/client/src/base/selection-service.ts
Fix di registration of selection listeners
Fixes https://github.com/eclipse-glsp/glsp/issues/1361
Nothing to test manually. A unit test hast been added to ensure that di selection listener registration is working as expected
=> GLSP-1361: Fix di registration of selection listeners

examples/workflow-standalone/app/example1.wf, packages/client/src/features/accessibility/view-key-tools/deselect-key-tool.ts
- Update example1.wf file to consistently use easy human readable ids to fix currently failing playwright tests and make testing overall easier
- Update `DeselectKeyListener`. Remove condition to check for active resize handles. Resize handles are now longer reseteted on default tool activatin/focus switch. As a consequence the `DeselectKeyListener` no longer has to consider them and can just always trigger deselection
Part of https://github.com/eclipse-glsp/glsp/issues/1369
=> GLSP-1369: Update example1.wf

CHANGELOG.md, package.json, packages/client/src/base/editor-context-service.ts, packages/client/src/base/focus/focus-tracker.ts
- Add `onFocusChanged` event to focus tracker and also expose it via EditorContextService
- Update documentation on `EditorContextService`. Also expose `onSelectionChanged` event via `EditorContextService` => `EditorContextService` becomes the central component to register for (most) GLSP event listeners https://github.com/eclipse-glsp/glsp/issues/1371
=> GLSP-1371: Introduce event for focus changes

packages/glsp-sprotty/src/re-exports.ts, packages/protocol/src/client-server-protocol/jsonrpc/base-jsonrpc-glsp-client.ts
- Ensure JsonrpcClientProxy is injectable in the glsp-sprotty context
Contributed on behalf of Axon Ivy AG
Part of https://github.com/eclipse-glsp/glsp/issues/1381
- Create an npm package that depends on the GLSP protocol but do not specify inversify as a dependency. Everything should still work.
=> Ensure no inversify-based code lands in the index

packages/client/src/features/accessibility/keyboard-pointer/keyboard-pointer-position.ts, packages/client/src/features/accessibility/keyboard-pointer/keyboard-pointer.ts, packages/client/src/features/tools/node-creation/container-manager.ts, packages/client/src/features/tools/node-creation/node-creation-module.ts, packages/client/src/features/tools/node-creation/node-creation-tool.ts, packages/glsp-sprotty/src/types.ts
- Added IContainerManager interface for easier customization
- Consume IContainerManager for dependency injection
- Extract isCreationAllowed submethod for element insertion checks
Resolves https://github.com/eclipse-glsp/glsp/issues/1388
Node creation should work as before, this should not impact the functionality at all.
--
=> GLSP-1388 Enhance extensibility of `ContainerManager`

packages/glsp-sprotty/src/re-exports.ts, packages/protocol/src/di/re-decorate.ts
Ensures that anyone with that imports '@eclipse-glsp/protocol/lib/di' will get the correctly decorated classes without the need to re-specify the decorations.
=> Ensure anyone who imports the di functionality gets decorated classes

examples/workflow-glsp/src/workflow-startup.ts, packages/client/src/features/accessibility/view-key-tools/movement-key-tool.ts, packages/client/src/features/debug/debug-bounds-decorator.tsx, packages/client/src/features/debug/debug-manager.ts, packages/client/src/features/debug/debug-module.ts, packages/client/src/features/element-template/mouse-tracking-element-position-listener.ts, packages/client/src/features/grid/grid-manager.ts, packages/client/src/features/grid/grid-module.ts, packages/client/src/features/select/select-mouse-listener.ts, packages/client/src/features/tool-palette/tool-palette.ts, packages/client/src/features/tools/change-bounds/change-bounds-manager.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool-feedback.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool-module.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool.ts, packages/client/src/features/tools/edge-edit/edge-edit-tool-feedback.ts, packages/client/src/features/tools/edge-edit/edge-edit-tool.ts, packages/client/src/features/tools/node-creation/container-manager.ts, packages/client/src/features/tools/node-creation/node-creation-tool.ts, packages/client/src/views/ggraph-view.tsx, packages/client/src/views/glsp-projection-view.tsx, packages/glsp-sprotty/src/types.ts
- Align interface + symbol usage for *Manager classes
- `ChangeBoundsManager`, `GridManager`, `DebugManager`
- Use bindAsService to ensure backward compatibility
- Update injects to use the symbol instead of the actual manager class
Resolves https://github.com/eclipse-glsp/glsp/issues/1393
Changing bounds, grid toggling and debug mode toggling should work as before, this should not impact the functionality at all.
--
=> GLSP-1393 Align Interface usage across *Manager classes

CHANGELOG.md, packages/client/src/base/mouse-position-tracker.ts
Ensure that the `GLSPMousePositionTracker` correctly calculates the diagram local mouse position
Ensure that resize/move still works as expected.
Also test the corner case with resizing/moving near/over the projection bars
If you want to verify the tracked position you can add a log point in the `GLSPMousePositionTracker.mouseMove` method
=> GLSP-1399: Fix MousePositionTracker

packages/client/src/features/tools/change-bounds/change-bounds-tool-move-feedback.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool.ts, packages/glsp-sprotty/src/types.ts
Fixes: https://github.com/eclipse-glsp/glsp/issues/1423
Per default change the behavior that all selected elements will be reset to it's origin location when one move is invalid. But add an `IMovementBehavior` type where this can be changed to the old style.
_Question:_ 
- Should also the red border feedback be on both elements?
- Better name for the options type / flag on the type?
Add to the `examples/workflow-standalone/src/di.config.ts`
```ts
export default function createContainer(options: IDiagramOptions): Container {
...
container.bind(TYPES.IMovementRestrictor).to(NoOverlapMovementRestrictor);
container.bind(TYPES.IMovementBehavior).toConstantValue({ allElementsNeedToBeValid: true }); //or false for the old behavior
return container;
}
```
_New behavior:_
_Old behavior:_
-   [x] …
=> GLSP-1423 Add MovementBehavior to control invalid multi element movements

packages/client/src/base/command-stack.ts, packages/client/src/base/feedback/feedback-action-dispatcher-default.ts, packages/client/src/base/model/diagram-loader.ts, packages/client/src/features/accessibility/toast/toast-tool.ts, packages/client/src/features/status/status-overlay.ts, packages/client/src/features/tool-palette/tool-palette.ts, packages/glsp-sprotty/src/api-override.ts
- Avoid unnecessary dispatch of empty `SetModelAction`. Await the initialize method of the action dispatcher instead (which already dispatches an empty model internally
- Fix behavior of `postRequestModel` hook to actually work as described in the model. Instead of requesting and awaiting the dispatch of the response `SetModelAction` we now simply dispatch the `RequestModelAction` and continue with the`postRequestModelHook`
- Use promise instead of listener for the model initalization constraint. This way we can await the `postModelInitialization` hook . I.e. the DiagramLoader.load methods actually completes once its completely finished (all hooks have been invoked and resolved)
- Fix action of startup UIExtensions. Instead of directly calling their show-Method, a corresponding …
=> GLSP-1427: Improve diagram loading and commmand handling

packages/client/src/base/selection-service.ts, packages/client/src/features/helper-lines/helper-line-manager-default.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool-move-feedback.ts, packages/client/src/features/tools/change-bounds/change-bounds-tool.ts, packages/client/src/features/tools/edge-edit/edge-edit-tool.ts, packages/client/src/utils/gmodel-util.ts
- Handle mouse down if we should be dragging as mouse up
- Reset feedback if selection has changed
-- Ensure element does not have to be selected to revert move
-- Add method for listeners to selection service
Fixes https://github.com/eclipse-glsp/glsp/issues/1426
See https://github.com/eclipse-glsp/glsp/issues/1426
=> Properly handle move feedback if mouse up happens outside window

packages/client/src/base/action-dispatcher.ts, packages/protocol/src/client-server-protocol/base-glsp-client.spec.ts, packages/protocol/src/client-server-protocol/base-glsp-client.ts, packages/protocol/src/client-server-protocol/glsp-client.ts, packages/protocol/src/client-server-protocol/jsonrpc/base-jsonrpc-glsp-client.spec.ts, packages/protocol/src/client-server-protocol/jsonrpc/base-jsonrpc-glsp-client.ts, packages/protocol/src/utils/event.spec.ts, packages/protocol/src/utils/event.ts
- Introduce `onCurrentStateChanged` event for `GLSPClient`
- Ensure that `start` and `initializeServer` behave as expected if they are called  again while the previous promise is still pending.
- Restructure members of the default implementations so that get/setters and their _property are grouped together
- Introduce a dedicated namespace for the `Event` interface with utility functions to
- listen on a certain event exactly once
- waitUntil a certain event is fired the next time
- Adapt test cases to verify new behavior
Also:
- Update `GLSPActionDispatcher` to use direct injection for registry instead of async provider
-   [ ] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration …
=> GLSP-1438: Improve GLSPClient default implementations

packages/client/src/features/routing/edge-router.ts
Remove the override of `applyInnerHandleMoves` in `GLSPManhattanEdgeRouter`. This workaround was introduced as a fix for https://github.com/eclipse-glsp/glsp-client/pull/200 but has since then also been fixed in base sprotty: https://github.com/eclipse-sprotty/sprotty/issues/310 therefore overriding is no longer necessary.
=> Remove workaround in GLPSManhattanEdgeRouter

packages/client/src/features/navigation/navigation-target-resolver.ts
Normalize source and target uris by striping a potential file:// prefix before comparing
Part of: https://github.com/eclipse-glsp/glsp/issues/1441
This change needs to be tested in the Theia integration.
(local link)
With this fix the go to next/previous node commands/context menu entries should now work as expected.
=> GLSP-1441: Fix NavigationTargetResolver uri handling

packages/client/src/base/action-handler-registry.ts, packages/client/src/base/default.module.ts, packages/client/src/base/ui-extension/ui-extension-registry.ts, packages/client/src/base/view/key-tool.ts, packages/client/src/base/view/mouse-tool.ts, packages/glsp-sprotty/src/types.ts, packages/protocol/src/di/lazy-injector.ts
- Remove usage of not-exported constant in lazy injector
- Fix constructor injection of classes that are overwritten to replace constructor injection with lazy injection. To pass the stricter type checks of newer inversify version we need to inject an empty array here.
This ensures that the code base is compatible with all 6.x versions of inversify and we can hard pin/resolve the version required for newer Theia versions while other integrations don't require any change.
Part of https://github.com/eclipse-glsp/glsp/issues/1449
Add a resolutions block in the root package. json
```ts
"resolutions": { "**/inversify":"^6.1.3"}
```
Build and start the application. Everything should still  work as expected.
-   [ ] This PR introduces a …
=> GLSP-1449: Ensure that codebase is compatible with inversify >= 6.1.3

CHANGELOG.md, examples/workflow-standalone/package.json, examples/workflow-standalone/scripts/start-example-server.ts, package.json, packages/client/package.json, packages/glsp-sprotty/package.json, packages/protocol/package.json, packages/protocol/src/client-server-protocol/jsonrpc/ws-connection-provider.ts, yarn.lock
- Update to inversify ^6.1.3
- Update to sprotty 1.4.0
Part of: https://github.com/eclipse-glsp/glsp/issues/1449
- Drop support for node 16
Part of: https://github.com/eclipse-glsp/glsp/issues/1456
Update changelog
=> GLSP-1449: Update inversify

examples/workflow-standalone/scripts/start-example-server.ts, examples/workflow-standalone/src/app.ts, examples/workflow-standalone/src/globals.d.ts, examples/workflow-standalone/webpack.config.js
This PR is for including host and port configuration to the example/standalone server start script, as well as to the standalone frontend app. Defaults are specified such that original operation should be unchanged.
I opted to parse the relevant command line arguments myself as opposed to with a library, because I felt it is a bit of overkill to introduce an extra dependency for parsing command line arguments. 
closes https://github.com/eclipse-glsp/glsp/issues/1410
From the `examples/workflow-standalone` dir, start the example server with something like `yarn ts-node scripts/start-example-server.ts --port 1234 --host 127.0.0.1` or similar, and build the frontend app with `GLSP_SERVER_PORT=1234 GLSP_SERVER_HOST=127.0.0.1 yarn build`.
The server should listen on the port and host …
=> Add host and port configuration

packages/client/css/glsp-sprotty.css
Works on https://github.com/eclipse-glsp/glsp/issues/1241
- It will fix the failing test 
- Trigger validation
- Move a node to be above another node
=> Remove important from sprotty css

examples/workflow-glsp/css/diagram.css
Set `user-select` to none to avoid blinking cursors and/or other indication for text selection when clicking on labels. (Default document text selection of svg text elements is not working anyways)
=> Update default styling for labels

packages/client/src/views/routing-point-handle-view.tsx
Follow-up for https://github.com/eclipse-glsp/glsp/issues/1490 Ensure that the unwanted sprotty reconnect handles are not rendered.
=> Hide sprotty sprotty reconnect handles

packages/client/css/glsp-sprotty.css
Chrome's default selection behavior when pressing the shift key messes with styles/selection hightlighting in the diagram
By setting user-select:none for the diagram svg we can fix this issue. Default html text selection does not work for svg text elements anyways, so this change does not break any existing behavior.
Holding shift an moving the mouse (e.g. using the MarqueeSelectionTool) should not mess up styling/text selection.
This is how it looks like on master using chrome:
https://github.com/user-attachments/assets/e73de25d-9b19-485b-9a26-ab0e9371d848
This if with the PR fix:
https://github.com/user-attachments/assets/2b2c2878-96b0-474e-82e1-946633c19a11
-   [ ] This PR introduces a breaking change (if yes, provide more details …
=> Fix text selection issues in chrome

packages/client/src/views/compartments.tsx
Update `StructuredCompartmentView` to render a rectangle with size 0,0 if either the width or height of the element is 0. This avoids that size migh end up in negatives (-1) after svg translations are applied.
Fixes https://github.com/eclipse-glsp/glsp/issues/1525
- Create a new Category
- Ensure that there are no console errors of the following form:
- Ensure that resizing and adding child nodes still works as expected.
=> GLSP-1525: Fix render error for new categories

packages/client/src/features/bounds/hbox-layout.ts, packages/client/src/features/bounds/vbox-layout.ts
Ensure that child layout options are only retrieved if the child has a layout feature
Fixes eclipse-glsp/glsp/issues/1530
=> GLSP-1530: Fix hGrab/vGrab layout calculation

packages/client/src/base/command-stack.ts, packages/client/src/base/default.module.ts, packages/client/src/base/editor-context-service.ts, packages/client/src/base/focus/focus-tracker.ts, packages/client/src/base/model/model-change-service.ts, packages/glsp-sprotty/src/api-override.ts, packages/glsp-sprotty/src/re-exports.ts, packages/glsp-sprotty/src/types.ts
Refactor our approach to handle model changes and introduce dedicated `IModelChangeService`.
- Extends the `ICommandStack` interface by adding an event to react to successfull command execution
- Introduce dedicated `IModelChangeService` to encapsulate model change handling from the `EditorContextService` similar to how we do it for the selection change and the `SelectionService`
- Refactor editor context, to use/forward to the model change service
In addition:
- Clean up disposal behavior of FokusTrack
Fixes eclipse-glsp/glsp/issues/1531
For testing a logger can be configured as event listener e.g:
-   [x] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)
Potentially …
=> GLSP-1531: Introduce viewport change event

packages/client/css/command-palette.css, packages/client/src/features/command-palette/command-palette.ts
Adjust CSS styling for the command palette to enable proper overflow without shifting the diagram itself.
Use relative position and absolute diagram bounds to avoid shifting the diagram if the command palette would overflow
Fixes https://github.com/eclipse-glsp/glsp/issues/1245
Trigger a command palette on an element that is near to the bottom or right edge:
Master:
PR:
=> GLSP-1245: Fix overflowing issue with command palette
