eclipse-glsp/glsp-client

- Jenkinsfile
Actual deployment will be provided in follow-up PR
> Resolve #1 Setup Jenkins CI

- src/features/tools/change-bounds-tool.ts
- src/features/tools/creation-tool.ts
- src/features/tools/drag-aware-mouse-listener.ts
- src/features/tools/edge-edit-tool.ts
Migrated from https://github.com/eclipsesource/graphical-lsp/pull/395/
> Improve extensibility of tool mouse listeners

- .nycrc
- .vscode/launch.json
- Jenkinsfile
- configs/mocha.opts
- package.json
- src/features/context-menu/menu-providers.spec.ts
- src/features/layout/layout-commands.spec.ts
- src/features/tool-feedback/change-bounds-tool-feedback.ts
- yarn.lock
Resolves #13 
Adds two tests specified in #15
> Add initial test setup #13

- package.json
- src/base/model/update-model-command.ts
- src/features/change-bounds/movement-restrictor.ts
- src/features/change-bounds/snap.ts
- src/features/tool-feedback/change-bounds-tool-feedback.ts
- src/features/tool-feedback/css-feedback.ts
- src/features/tool-feedback/di.config.ts
- src/features/tools/change-bounds-tool.ts
- src/features/tools/creation-tool.ts
- src/features/tools/delete-tool.ts
- src/features/tools/drag-aware-mouse-listener.ts
- src/features/tools/edge-edit-tool.ts
- src/index.ts
- yarn.lock
- Add support for snapping feature of sprotty
- Rework NoOverlapMovementRestrictor
- Add feedback for element overlap
- FIx issue that  triggered a ChangeBoundsAction on click
> #5 #8 Add snapping feature and rework movement restrictor

- src/base/di.config.ts
- src/base/editor-context.ts
- src/features/command-palette/server-command-palette-provider.ts
- src/features/context-actions/action-definitions.ts
- src/features/context-menu/delete-element-context-menu.ts
- src/features/context-menu/server-context-menu-provider.ts
- src/features/copy-paste/copy-paste-actions.ts
- src/features/copy-paste/copy-paste-handler.ts
- src/features/copy-paste/di.config.ts
- src/index.ts
- src/model-source/websocket-diagram-server.ts
- src/types.ts
eclipse-glsp/glsp#12
To test this change, you'll also need the following changes:
* eclipse-glsp/glsp-server#35
* eclipse-glsp/glsp-examples#25
* eclipse-glsp/glsp-theia-integration#16
> glsp#12 Add initial support for copy & paste

- src/features/tools/edge-edit-tool.ts
- Rename ReconnectEdgeListener to EdgeEditListener and implement it as DragawareMouseListener
- Improve activation/deactivation of related listeners (on active if an suitable edge is selected
> Refactor edge edit tool

- src/features/copy-paste/copy-paste-context-menu.ts
- src/features/copy-paste/copy-paste-handler.ts
- src/features/copy-paste/di.config.ts
- src/index.ts
- src/model-source/glsp-server-status.ts
- src/types.ts
https://github.com/eclipse-glsp/glsp/issues/22
> Fix failing copy for SVG selection (glsp#22)

- src/features/tool-feedback/creation-tool-feedback.ts
The DrawFeedbackEdge action now takes an EdgeSchema as additional argument which enables the customiztion of the resulting feedback edge. If no schema is passed a default implementation is used
> Allow customization of feedback edge

- src/base/di.config.ts
- src/base/selection-clearing-mouse-listener.ts
- src/index.ts
> Clear selection on diagram click

- src/features/tools/creation-tool.ts
Ensure that additional args of trigger actions are properly dispatched to the server. This is achieved by caching the entire trigger action instead of just the element type id.
In addition, throw an error if the is activated while the trigger action is still undefined
> Update creation tools

- src/model-source/glsp-server-status.ts
- Fixes eclipse-glsp/glsp/issues/48
Please note this change belongs to this group:
- https://github.com/eclipse-glsp/glsp-server/pull/51
- https://github.com/eclipse-glsp/glsp-examples/pull/40
- https://github.com/eclipse-glsp/glsp/pull/49
- https://github.com/eclipse-glsp/glsp-theia-integration/pull/27
> Add new action for server messages

- src/features/copy-paste/copy-paste-context-menu.ts
- src/model-source/glsp-server-status.ts
So far we only sent a server status action, but separating server actions and messages, we should also send a message in addition.
Also this change introduces an enum type for severity.
> Send message on paste to notify user

- src/features/copy-paste/copy-paste-handler.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/52
> Fix usage of UUID for copy&paste

- src/features/tool-palette/tool-palette.ts
See also https://github.com/eclipse-glsp/glsp-server/pull/53 for the server-side change.
Concerns https://github.com/eclipse-glsp/glsp/issues/51
> Order tool items 1. by sortString & 2.by alphabet

- src/features/select/selection-service.spec.ts
- src/features/select/selection-service.ts
- Fixes eclipse-glsp/glsp/issues/44
> Provide test cases for selection-service and adapt where necessary

- package.json
- yarn.lock
Resolves eclipse-glsp/glsp/issues/53
> Pin version of UUID

- src/features/tools/change-bounds-tool.ts
- Improve customizability of change-bound-tool
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> Ensure mouse cursor can be restored more easily if hidden due to resize

- src/features/context-menu/di.config.ts
- src/features/context-menu/selection-service-aware-context-menu-mouse-listener.ts
- src/features/copy-paste/copy-paste-context-menu.ts
- src/features/validation/di.config.ts
- src/features/validation/marker-navigator.spec.ts
- src/features/validation/marker-navigator.ts
- src/index.ts
- src/utils/marker.ts
- src/utils/smodel-util.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/64
> Support issue marker navigation

- src/features/validation/validate.ts
Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>
> Fix correct setting of severity cssClass on diagram validation

- src/base/operations/operation.ts
- src/features/tools/change-bounds-tool.ts
- src/model-source/websocket-diagram-server.ts
see eclipse-glsp/glsp/issues/76 &
eclipse-glsp/glsp-server/pull/60
> Add support for compound operations

- src/base/selection-clearing-mouse-listener.ts
Resolves eclipse-glsp/glsp/issues/71
> Fix broken viewport under IE11

- src/features/copy-paste/copy-paste-handler.ts
It looks like the srcElement that we've used before to determine whether we should active GLSP copy has changed and is now, in Theia, always the Theia icon.
We should check the `document.activeElement` instead to be more resilient.
Fixes https://github.com/eclipse-glsp/glsp/issues/80
> Fix copy & paste

- css/tool-palette.css
- src/features/tool-palette/tool-palette.ts
Make tool palette collapsible and scrollable; 
Add search field for palette entries
> Palette improvements

- src/features/tools/creation-tool.ts
The node creation tool now snaps the location before sending the create operation to the client. Also: Refactor unnecessary constructor injection in creation tools.
Part of eclipse-glsp/glsp/issues/42
> #42 Element creation should respect grid snapping settings

- src/features/tool-palette/tool-palette.ts
Add widget ID to the palette search field ID to ensure uniqueness in case of multiple open editors.
> Palette search field

- src/model-source/websocket-diagram-server.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/21
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> #21: Remove unused actions

- src/base/actions/protocol-actions.ts
- src/model-source/glsp-diagram-server.ts
Follow-up for eclipse-glsp/glsp/issues/96
> #96 Introduce InitializeClientSessionAction

- packages/client/src/features/tool-palette/tool-palette.ts
The Palette Tool is now focused when it's activated, and it can handle the Escape key-press (Thus disabling itself).
> #110 Improve Palette-tool disabling

- packages/client/css/glsp-sprotty.css
- packages/client/src/features/tool-palette/tool-palette.ts
- packages/client/src/features/tools/delete-tool.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/125
Fixes https://github.com/eclipse-glsp/glsp/issues/84
Signed-off-by: Philip Langer <planger@eclipsesource.com>
> Add tooltips in palette and fix mouse delete tool

- examples/workflow-sprotty/src/di.config.ts
- packages/client/src/features/model-source-watcher/di.config.ts
- packages/client/src/features/model-source-watcher/model-source-changed-action-handler.ts
- packages/client/src/features/model-source-watcher/model-source-changed-action.ts
- packages/client/src/index.ts
https://github.com/eclipse-glsp/glsp/issues/134
> Handle model source change notification

- packages/client/src/features/navigation/navigation-target-resolver.ts
Fixes eclipse-glsp/glsp/issues/143
> Fix #143 Properly decode navigation URis

- examples/workflow-glsp/src/di.config.ts
https://github.com/eclipse-glsp/glsp/issues/123
> Removes needsClientLayout flag

- README.md
- examples/workflow-glsp/package.json
- examples/workflow-glsp/scripts/download.ts
- package.json
- yarn.lock
fixed #171
Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>
> Added download script for server

- examples/workflow-glsp/scripts/download.ts
fixed #174
Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>
> Removed unused assignment

- packages/client/src/base/args.ts
https://github.com/eclipse-glsp/glsp/issues/194
> Add SArgumentable interface denoting elements that contain args

- packages/client/src/features/save/save.ts
Part of eclipse-glsp/glsp/issues/208
> #208 Add `fileUri` to `SaveModelAction`

- packages/client/src/base/operations/operation.ts
Fixes eclipse-glsp/glsp/issues/212
> #212 Add missing typeguard functions for operations

- examples/workflow-glsp/package.json
- examples/workflow-standalone/package.json
- packages/client/package.json
- packages/protocol/package.json
Part of eclipse-glsp/glsp/issues/246
> #246 Use generic stand-in contributor

- .github/workflows/codeql-analysis.yml
Setup the "CodeQL Analysis" toolcahin that is offered directly by Github  to use Actions for automated security analysis.
Part of eclipse-glsp/glsp/issues/237
> #237 Setup automated code scanning alerts

- SECURITY.md
> #391 Create Security.MD file

- packages/protocol/src/action-protocol/client-notification.ts
- packages/protocol/src/action-protocol/model-structure.ts
Follow-up for eclipse-glsp/glsp/issues/256
> #256 Add missing construtor for client notifcation actions

- packages/protocol/src/action-protocol/model-structure.ts
- packages/protocol/src/action-protocol/types.ts
- packages/protocol/src/utils/array-util.ts
& extend array utils library
Follow-up for eclipse-glsp/glsp/issues/256
> #256 Add utility constants for protocol types

- packages/protocol/src/action-protocol/element-text-editing.ts
Contributed on behalf of STMicroelectronics.
> Add text to ApplyLabelEditOperation

- examples/workflow-standalone/src/app.ts
- packages/protocol/src/action-protocol/element-text-editing.ts
- packages/protocol/src/action-protocol/element-type-hints.ts
- packages/protocol/src/action-protocol/element-validation.ts
- packages/protocol/src/action-protocol/mode-layout.ts
- packages/protocol/src/action-protocol/model-data.ts
Part of eclipse-glsp/glsp/issues/257
https://github.com/eclipse-glsp/glsp-server/pull/142
> #257 Align client& server protocol

- packages/client/src/base/action-dispatcher.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/474
> Don't initialize dispatcher with resolved promise

- packages/client/src/features/layout/di.config.ts
- packages/client/src/features/layout/hbox-layout.ts
- Implement HBoxLayouterExt, similar to the existing VBoxLayouterExt
Fixes eclipse-glsp/glsp/issues/443
Also fixes eclipse-glsp/glsp/issues/567
> 443: Implement extended HBox layouter

- packages/client/src/base/container-modules.ts
- packages/client/src/features/tools/di.config.ts
- packages/client/src/features/tools/enable-default-tools-on-focus-loss.ts
- packages/client/src/index.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/547
> Enable default tools on focus loss

- packages/client/src/features/tool-feedback/edge-edit-tool-feedback.ts
Fix for: https://github.com/eclipse-glsp/glsp/issues/613
Also snap the routing handle before send it to the server.
With this change it will be possible to draw a straight line out of a polyline edge.
> Issue-613 Fix snap routing handles

- examples/workflow-glsp/scripts/config.json
- examples/workflow-glsp/scripts/download.ts
- examples/workflow-glsp/tsconfig.json
Refactor configuration for the download server-script into separate JSON resource. This makes it easier to maintain and offers a simple approach to update the configuration in automated (CI) jobs
> Refactor download-server script

- packages/client/src/features/export/glsp-svg-exporter.ts
- packages/client/src/features/tools/di.config.ts
- SVG element is not properly detected as it is nested
- SVG element is not properly copied when it does not have an ID
https://github.com/eclipse-glsp/glsp/issues/642
> #642: Fix export SVG handling

- packages/protocol/src/glsp-client.ts
Increment protocol version to 1.0.0.
Part of https://github.com/eclipse-glsp/glsp/issues/706
Signed-off-by: Olaf Lessenich <olessenich@eclipsesource.com>
> GH-706 Update protocol version

- CHANGELOG.md
- examples/workflow-standalone/package.json
- examples/workflow-standalone/src/app.ts
- examples/workflow-standalone/webpack.config.js
- packages/protocol/package.json
- packages/protocol/src/jsonrpc/base-jsonrpc-glsp-client.ts
- packages/protocol/src/jsonrpc/glsp-jsonrpc-client.ts
- yarn.lock
Reverts eclipse-glsp/glsp-client#210
> Revert "Update to latest vscode-json-rpc version"

- CHANGELOG.md
- Jenkinsfile
- examples/workflow-standalone/package.json
- examples/workflow-standalone/src/app.ts
- examples/workflow-standalone/webpack.config.js
- package.json
- packages/protocol/package.json
- packages/protocol/src/jsonrpc/base-jsonrpc-glsp-client.ts
- packages/protocol/src/jsonrpc/glsp-jsonrpc-client.ts
- yarn.lock
- vscode-ws-jsonrpc requires Node >= 16.11.0
> Update to vscode-ws-jsonrpc 2.0.1, increase Node minimum to >=16.11.0

- examples/workflow-glsp/src/di.config.ts
- examples/workflow-glsp/src/model.ts
- examples/workflow-standalone/src/app.ts
- examples/workflow-standalone/src/url-parameters.ts
- packages/client/README.md
- packages/client/src/base/selection-clearing-mouse-listener.ts
- packages/client/src/features/command-palette/command-palette-tool.ts
- packages/client/src/features/save/model.ts
- packages/client/src/features/source-model-watcher/di.config.ts
- packages/client/src/features/validation/issue-marker.ts
- packages/client/src/lib/model.ts
- packages/client/src/utils/html-utils.ts
- packages/client/src/views/base-view-module.ts
- packages/client/src/views/glsp-projection-view.tsx
- packages/client/src/views/index.ts
- packages/protocol/README.md
- packages/protocol/src/glsp-client.ts
- Execute the newly introduced [script](https://github.com/eclipse-glsp/glsp/tree/master/dev-packages/cli#checkheaders) to check and fix copyright header violations
- Update package READMEs
> Fix copyright header violations

- packages/protocol/src/action-protocol/base-protocol.ts
- packages/protocol/src/utils/type-util.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/879
Checkout the [TS playground](https://www.typescriptlang.org/play?#code/FAehAICEFMDMHsBO1iwK4DsDGAXAlvBuAEZxLQAUAlAN7DgPg4CeADtOAIIbMDyxAK2i4AvOABKwpABMAPAAVE8dohYBpaMwA0mANYZ4AdwwA+YPUZZCAZxzhMWABbDd0aQC5ufQcJwia1vAAttCKytCqzO6Q8PAANtAAhhgAvhYMDs5YrtIAdIEhYSosIgCsDGD22Fk54KxKxczgiVhY0NbWdfAdeMQJueAAogBu0ESGSNbQWuB4OJ2s3da9CUzwzT0A5kSJ4NJ4sLARY3b14ZFMbNADAMrr7VMY+IlxcU04jnidX0zO4NaJEIbezLDCbcAAA2SzAh5kY4ASdmh-CEuE8PBRvjENDS6XAVgwtlmGDieAw0AAKld3DQEPB3LZEGTNil-HT3AAiYiJRAclIAbjxyJ8omJpPJVPYgrxZJwEVgLQ4AEknvLFXR4fD2YzmXjcfCCUTZWq2pLoO4VXLEAq2mzYpzubyBUKMSK-MSrTbKVd+ZrNZUACLwdrgAx2CaIXTgBCIOpxRJkj0mjgsdjWcx4rDxjrgADC2esGr90ftOrBIi5PI5erhlhsdiziQ6ZrE5MMeYL1F94DAQZDYfAEajMfxBeJtmSbXT8OFqPdjebV1rDHMuMqAHU5o5wPJxPjHMlNu1UA58IRB1vFNQiwxUxwvJjRfA …
> Ensure that all objects are assignable to the `AnyObject` type

- examples/workflow-glsp/src/direct-task-editing/direct-task-editor.ts
Relates to https://github.com/eclipse-glsp/glsp/issues/864
> Replace 'ApplyTaskEditOperation' with direct use of 'EditTaskOperation'

- CHANGELOG.md
- examples/workflow-standalone/src/app.ts
- packages/protocol/package.json
- packages/protocol/src/index.ts
- packages/protocol/src/jsonrpc/websocket-connection.ts
- packages/protocol/src/utils/type-util.ts
- yarn.lock
Replace vscode-ws-jsonrpc with own implementation
Part of https://github.com/eclipse-glsp/glsp/issues/944
> Provide own websocket vsode-jsonrpc connection

- CHANGELOG.md
- packages/client/src/features/tool-palette/tool-palette.ts
- packages/client/src/features/validation/validate.ts
- packages/protocol/src/action-protocol/element-validation.spec.ts
- packages/protocol/src/action-protocol/element-validation.ts
Also track feedback by reason to replace only those on `SetMarkersAction` that have the same reason.
https://github.com/eclipse-glsp/glsp/issues/980
For review, please see [the comment on which changes belong together](https://github.com/eclipse-glsp/glsp/issues/980#issuecomment-1516867263).
> Add a reason for requesting and setting markers

- examples/workflow-glsp/src/di.config.ts
- package.json
- packages/client/css/autocomplete-palette.css
- packages/client/css/glsp-sprotty.css
- packages/client/package.json
- packages/client/src/base/auto-complete/auto-complete-widget.ts
- packages/client/src/features/accessibility/di.config.ts
- packages/client/src/features/accessibility/search/di.config.ts
- packages/client/src/features/accessibility/search/search-palette.ts
- packages/client/src/features/accessibility/search/search-tool.ts
- packages/client/src/features/autocomplete-palette/autocomplete-suggestion-providers.ts
- packages/client/src/features/autocomplete-palette/base-autocomplete-palette.ts
- packages/client/src/index.ts
- yarn.lock
This PR is part of my diploma research conducted at the [Model Engineering lab](https://me.big.tuwien.ac.at/) of TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/). It introduces the **search** functionality.
1. Focus is on viewport or element(s)
2. Use the shortcut  `CTRL + F` to display search field
3. Type in search term (label or type of elements)
4. Elements which fulfill the condition will be outlined, elements which **do not** fulfill the condition will become transparent.
5. Use arrow up or down to iterate through the returned list --> will jump to corresponding element and outline it
@martin-fleck-at, @ndoschek
> Add keyboard support for searching elements

- examples/workflow-glsp/README.md
Update outdated information section in workflow example README
> Update workflow example README

- examples/workflow-standalone/package.json
- package.json
- packages/protocol/src/client-server-protocol/jsonrpc/base-jsonrpc-glsp-client.ts
- yarn.lock
Also: Disable logging of base json-rpc-client proxy per default
> GLSP-1026 Use new bundled workflow-server package

- packages/client/src/features/select/select-feedback-action.ts
- packages/client/src/features/select/selection-service.ts
- packages/client/src/features/tools/marquee-mouse-tool.ts
- packages/protocol/src/action-protocol/element-selection.spec.ts
- packages/protocol/src/action-protocol/element-selection.ts
- Introduce optional flag that indicates deselection of all elements
- Introduce convenience creation methods for SelectAll action
https://github.com/eclipse-glsp/glsp/issues/979
> GLSP-979: Introduce 'deselectAll' flag for SelectAction

- packages/client/src/features/select/selection-service.ts
- packages/client/src/features/tool-palette/tool-palette.ts
- Fix minor issue with default button not being present before init
Fixes https://github.com/eclipse-glsp/glsp/issues/1048
> GLSP-1048: Keep focus if it was taken deliberately through an action

- examples/workflow-standalone/scripts/start-example-server.ts
Ensure that old server versions are properly removed before downloading a new version.
> Fix download server script

- packages/client/src/features/bounds/bounds-module.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/1031
> GLSP-1031: Fix wrong binding in bounds-module

- examples/workflow-glsp/package.json
- examples/workflow-standalone/package.json
- package.json
- packages/client/package.json
- packages/glsp-sprotty/package.json
- packages/protocol/package.json
Part of eclipse-glsp/glsp/issues/845
> GLSP-845: Update next version publishing

- packages/client/src/base/command-stack.ts
- packages/client/src/base/default.module.ts
- packages/client/src/base/selection-service.ts
- packages/glsp-sprotty/src/types.ts
Replace `ISModelRootListener` with `IGModelRootListener` and add deprecation layer
> GLSP-1170: Deprecate `ISModelRootListener`

- packages/client/src/base/auto-complete/auto-complete-widget.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/1177
> Set suggestion container position to `fixed`

- packages/protocol/package.json
- yarn.lock
Pin sprotty protocol version to 1.0.0
(Part of #https://github.com/eclipse-glsp/glsp/issues/1223)
Has already been approved but somehow was not merged into master
> Pin sprotty protocol version to 1.0.0

- examples/workflow-glsp/package.json
- examples/workflow-standalone/package.json
- packages/client/package.json
- packages/protocol/package.json
- yarn.lock
Ensure that 1.0.0 of sprotty-protocol is used in all client pacakges Part of https://github.com/eclipse-glsp/glsp/issues/1223
Nothing particular to test. Building + starting the example application should still work as before
> GLSP-1223 Align sprotty-protocol version

- packages/client/src/features/validation/validate.ts
Ensures that validation markers are properly reinitialized on model update.
Fixes https://github.com/eclipse-glsp/glsp/issues/1290
The previous approach only cleared markers for with the same `reason` as the new `SetMarkersAction`. 
This lead to double rendering of marker with other reasons.
Details:
Assume that we have markers applied to the model triggered by `batch` validation and now we trigger the live validation 
due to a model update.
- When the client processes the update it reapplies the markers from the previous batch and live validation
- Then the `SetMarkersAction` is processe which in terms calls `registerValidationFeedback`.
Register validation feedback now only clears the validation markers for the `live` reason, but then applies
both the new live markers and the old batch …
> Ensure that markers are properly reinitialized on update

- lerna.json
Fixes https://github.com/eclipse-glsp/glsp/issues/1295
> GLSP-1295 Fix next version publishing

- examples/workflow-glsp/src/workflow-diagram-module.ts
- examples/workflow-glsp/src/workflow-views.tsx
- packages/client/src/features/accessibility/move-zoom/move-handler.ts
- packages/client/src/features/change-bounds/movement-restrictor.ts
- packages/client/src/features/element-template/mouse-tracking-element-position-listener.ts
- packages/client/src/features/helper-lines/helper-line-feedback.ts
- packages/client/src/features/helper-lines/model.ts
- packages/client/src/features/layout/layout-elements-action.ts
- packages/client/src/features/viewport/reposition.ts
- packages/client/src/utils/geometry-util.ts
- packages/client/src/utils/gmodel-util.ts
- packages/client/src/utils/viewpoint-util.ts
- packages/protocol/src/sprotty-geometry-bounds.spec.ts
- packages/protocol/src/sprotty-geometry-bounds.ts
- packages/protocol/src/sprotty-geometry-dimension.spec.ts
- packages/protocol/src/sprotty-geometry-dimension.ts
- packages/protocol/src/sprotty-geometry-point.spec.ts
- packages/protocol/src/sprotty-geometry-point.ts
- packages/protocol/src/utils/geometry-movement.spec.ts
- packages/protocol/src/utils/geometry-movement.ts
- packages/protocol/src/utils/geometry-util.ts
- packages/protocol/src/utils/geometry-vector.spec.ts
- packages/protocol/src/utils/geometry-vector.ts
- packages/protocol/src/utils/index.ts
- Extend functions for Bounds, Dimensions, and Point
- Provide types and functions for Vector and Movement
Fixes https://github.com/eclipse-glsp/glsp/issues/1322
- Check if tests are running through and all adapted layouting classes still produce the same result.
-
> Provide Geometry utility classes

- packages/glsp-sprotty/src/re-exports.ts
Ensure that align feature is exported from sprotty
> Ensure that align feature is exported from sprotty

- examples/workflow-glsp/src/model.ts
- packages/client/src/features/change-bounds/model.ts
Minor fix in ResizeHandleLocation.ALL
Check that ResizeHandleLocation.ALL does not return other constants or functions in the same namespace.
> Minor fix in ResizeHandleLocation.ALL

- packages/client/src/features/element-template/mouse-tracking-element-position-listener.ts
- packages/client/src/features/export/glsp-svg-exporter.ts
- packages/client/src/features/tools/node-creation/container-manager.ts
- packages/client/src/features/tools/node-creation/insert-indicator.ts
- packages/client/src/features/tools/node-creation/node-creation-tool.ts
- packages/protocol/src/sprotty-geometry-bounds.spec.ts
- packages/protocol/src/sprotty-geometry-bounds.ts
- Ensure we render/unhide tracked ghost element as soon as possible
- Add ghost element bounds data to arguments sent to server
- Ensure we render/unhide tracked ghost element as soon as possible > only move mouse from tool palette to the graph without moving it on the graph
- Add ghost element bounds data to arguments sent to server > debug and check what is sent to or received on the server side
> Minor Improvements

- examples/workflow-standalone/tsconfig.json
- package.json
- packages/client/src/base/model/model-registry.ts
- packages/client/src/features/validation/issue-marker.ts
- packages/glsp-sprotty/package.json
- packages/glsp-sprotty/src/feature-modules.ts
- packages/glsp-sprotty/src/re-exports.ts
- packages/glsp-sprotty/src/svg-views-override.tsx
- packages/protocol/package.json
- packages/protocol/src/re-exports.ts
- yarn.lock
Mostly non-breaking changes. Some definitions have moved to the sprotty-protocol package. However, we can mitigate all potential breaks with our @eclipse-glsp/sprotty reexport.
Fixes https://github.com/eclipse-glsp/glsp/issues/1253
-   [x ] This PR should be mentioned in the changelog
> Update to Sprotty 1.2.0

- packages/client/src/features/viewport/viewport-handler.ts
Properly CSS escape the root id before using it as query selector
> Fix RestoreViewPortHandler

- packages/client/src/features/tools/edge-creation/edge-creation-tool.ts
- packages/client/src/features/tools/node-creation/node-creation-tool.ts
> Improve extensibility of creation tools

- Jenkinsfile
- package.json
A wrong lint:ci script has been pushed on accident. This replaces the script with the correct one so that the Jenkins build can pick up linting issues
> Use correct lint:ci command

- CHANGELOG.md
- packages/client/src/features/tools/marquee-selection/marquee-behavior.spec.ts
- packages/client/src/features/tools/marquee-selection/marquee-behavior.ts
- packages/client/src/features/tools/marquee-selection/marquee-mouse-tool.ts
- packages/client/src/features/tools/marquee-selection/marquee-selection-module.ts
- packages/protocol/src/utils/type-util.ts
Centralize Marquee selection behavior for improved customization
- Ensure that Marquee Selection works as before.
> Centralize Marquee selection behavior for improved customization

- .github/workflows/e2e.yml
- README.md
Add github actions workflow for E2E testing with glsp-playwright
Part of https://github.com/eclipse-glsp/glsp/issues/1287
> GLSP-1287: Add CI job for E2E tests

- .github/workflows/e2e.yml
> Update action workflows

- packages/client/src/features/export/glsp-svg-exporter.ts
- packages/glsp-sprotty/package.json
- packages/protocol/package.json
- packages/protocol/src/action-protocol/model-saving.ts
- yarn.lock
Update to latest sprotty release
Fixes https://github.com/eclipse-glsp/glsp/issues/1429
> GLSP-1429: Update to sprotty 1.3.0

- examples/workflow-glsp/css/diagram.css
- examples/workflow-standalone/css/diagram.css
- packages/client/css/glsp-sprotty.css
- packages/client/css/keyboard.css
- packages/client/css/search.css
- packages/client/src/features/accessibility/keyboard-grid/keyboard-grid.ts
- packages/client/src/features/accessibility/search/search-palette-module.ts
Removes `!important` from accessibility css
Works on https://github.com/eclipse-glsp/glsp/issues/1241
Test Accessibility:
- Search (there is a different bug, already fixed by https://github.com/eclipse-glsp/glsp/issues/1377)
- Navigation
> Remove important from accessibility css

- packages/client/src/views/base-view-module.ts
- packages/client/src/views/routing-point-handle-view.tsx
- packages/glsp-sprotty/src/re-exports.ts
Closes https://github.com/eclipse-glsp/glsp/issues/1490
Check created routing handles
Before:
After:
Fix the test cases.
> Prevent rendering of sprotty reconnect handle

- packages/client/src/features/tools/node-creation/container-manager.ts
Closes https://github.com/eclipse-glsp/glsp/issues/1488
Add the following to the node-server 
```
// examples/workflow-server/src/common/workflow-diagram-configuration.ts
{
elementTypeId: DefaultTypes.GRAPH,
deletable: false,
reparentable: false,
repositionable: false,
resizable: false,
containableElementTypeIds: [types.MANUAL_TASK]
},
```
Test it with and without the fix. Without the fix, you can still add anything to the root.
> Include root as a findable container for the container manager

- packages/client/src/base/auto-complete/auto-complete-widget.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/1495
Triggers on change event for autocompleter
Open the search palette and go through the list
> Allow to listen to selection changes in autocompleter

- packages/client/src/features/layout/trigger-layout-action-handler.ts
Ensure we provide selected element ids as part of layout operation
> Ensure we provide selected element ids as part of layout operation
